### ISSUE TITLE
Need code coverage analysis

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#108]
Currently our tests have very poor coverage over the codebase (filed as #109).  To help track work to address this, we should first introduce automated code coverage analysis using something like simplecov and CodeClimate: https://docs.codeclimate.com/docs/configuring-test-coverage

Although if there is a better alternative to CodeClimate then I'm totally open to it.

**Comment by aspiers** [comment]
However please note I have marked this for M2 since we have far more urgent tasks right now!!

**Comment by aspiers** [comment]
In #109, [**@baob**](https://github.com/baob) commented on [November 22, 2019 12:54 PM](https://github.com/swapmyvote/swapmyvote/issues/109#issuecomment-557521090 "2019-11-22T12:54:54Z - Replied by Github Reply Comments"):
> I could be way out of date on this, but in the past I've used SimpleCov and tied it in to Guard ... though guard is probably best applied when we have near to 100% coverage (say 80/90 ?) to keep us on track, rather than getting us to that point.

Yes simplecov is a good option and has the advantage of feeding in to the CodeClimate SaaS as described in https://docs.codeclimate.com/docs/configuring-test-coverage.  This would allow both offline coverage analysis (manually or via Guard), and automatic online analysis for PRs.

**Comment by stevebaxter** [comment]
Nice!
