### ISSUE TITLE
Check whether swap partner names are redacted in the right places.

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#110]
I merged #104 which was a beautiful implementation of name redaction to address #47.  However I might have been a little too hasty in merging since @threedaymonk wrote:

> I think I've captured all the locations in which the name is displayed before a swap is confirmed, but it would be good if someone who is more familiar with the app could check that I (a) haven't missed any, and (b) haven't been too assiduous and redacted names where they shouldn't be.

and I didn't do that prior to merging.

Taking a look now, I see that names are [redacted when a swap is confirmed by email](https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user_mailer/swap_confirmed.html.haml), but [not via the web UI](https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user/vote/show.html.haml), nor [when a swap is cancelled by email](https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user_mailer/swap_cancelled.haml).  There may be other inconsistencies, so we need a full review of this.

@tdg Based on how you worded #47, it sounds like you envisioned redaction only applying *prior* to swaps being confirmed; is that right?  If so we can [unredact](https://www.youtube.com/watch?v=2aINa6tg3fo) the confirmation email.

@threedaymonk If this isn't too boring, perhaps you could run with it?

**Comment by threedaymonk** [comment]
I've opened a draft pull request [here](https://github.com/swapmyvote/swapmyvote/pull/111).

So far, it only removes redaction in the confirmation email. Are there any other places that need changing?

**Comment by tdg** [comment]
> So far, it only removes redaction in the confirmation email. Are there any other places that need changing?

- [ ] on the /user page once partner has confirmed 
- [ ] in reminder emails before and on the day of the election
- [ ] in 'I've voted for you' email on the day of the election

I think these are the main ones…

**Comment by tdg** [comment]
Also, 
- [ ] (Name) has cancelled swap

**Comment by threedaymonk** [comment]
@tdg none of those should be redacted?

**Comment by threedaymonk** [comment]
@tdg in fact, if you could write next to each of those whether they should be redacted or unredacted, it'll be a lot easier!

**Comment by tdg** [comment]
> @tdg none of those should be redacted?

That's right - and amended above (apols for confusion - your question made sense to answer, but in retrospect I see what you mean!)

**Comment by tdg** [comment]
The principle is, you don't get to know someone's name until they and you have both confirmed you would like to swap with each other. 

Once confirmed, we introduce you to each other with each other's full name. 

Having done that, we then don't redact that person's name to you at any point (cos that would be odd)

**Comment by threedaymonk** [comment]
This is going to take me a while. It's easy, except

- I'm not familiar with this app
- I don't know which templates are (re)used at which stage(s)
- There are no useful high level tests I can hook into to actually assert this

**Comment by threedaymonk** [comment]
OK, I think I've worked out a better strategy: delegate the name to the swap, and let the swap determine whether or not to redact. There's a few cases where the template uses a user directly, but I think this will drastically reduce the complexity and scope for error everywhere else.

**Comment by tdg** [comment]
I like the simplicity of that idea. At the point that a swap is confirmed, the users should be able to reach out to each other on social. So they would get each others' names anyway, and it might feel strange that we are still redacting them? 

Perhaps we can cover that feeling with copy that says 'we don't display your full name to your voting partner within the site. However, once your swap is confirmed, you will be able to visit each others' public social media profile, which may include your full name. At this point, you can reach out to each other on social media, where you can introduce yourself more fully'

**Comment by aspiers** [comment]
[**@threedaymonk**](https://github.com/threedaymonk) commented on [November 25, 2019 1:07 PM](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-558147174 "2019-11-25T13:07:45Z - Replied by Github Reply Comments"):
> This is going to take me a while. It's easy, except
> 
> - I'm not familiar with this app

Hah, I think you maybe underestimate yourself - you already figured out everything you need to know with zero help ;-)

> - I don't know which templates are (re)used at which stage(s)

They're all under `app/views/` and it's pretty self-explanatory just by reading the text of each.

```
$ git grep -l '\.redacted_name' app/views/
app/views/user/swaps/_swap_profile.html.haml
app/views/user/swaps/new.html.haml
app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/swap_not_confirmed.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
```

> - There are no useful high level tests I can hook into to actually assert this

True but I'm not sure tests would help much here.  We could write view specs but they'd just have to exactly mirror the changes required in the code, so wouldn't add any obvious value.

[**@threedaymonk**](https://github.com/threedaymonk) commented on [November 25, 2019 5:35 PM](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-558261104 "2019-11-25T17:35:24Z - Replied by Github Reply Comments"):
> OK, I think I've worked out a better strategy: delegate the name to the swap, and let the swap determine whether or not to redact. There's a few cases where the template uses a user directly, but I think this will drastically reduce the complexity and scope for error everywhere else.

Maybe I'm wrong but this sounds more complicated to me.  All we need right now is literally to add to your PR #111 changes of `.redacted_name` to `.name` in the 4 places Tom listed above.  So that's about 4 lines of code to change, right?

[**@tdg**](https://github.com/tdg) commented on [November 25, 2019 5:41 PM](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-558263498 "2019-11-25T17:41:39Z - Replied by Github Reply Comments"):
> I like the simplicity of that idea. At the point that a swap is confirmed, the users should be able to reach out to each other on social. So they would get each others' names anyway, and it might feel strange that we are still redacting them? 

Right.

> Perhaps we can cover that feeling with copy that says 'we don't display your full name to your voting partner within the site. However, once your swap is confirmed, you will be able to visit each others' public social media profile, which may include your full name. At this point, you can reach out to each other on social media, where you can introduce yourself more fully'

On the one hand I can see the appeal of giving users the choice of when/whether their names are redacted.  On the other hand it just adds extra complexity to the UI and I'm not convinced it's worth it.  We want the whole process to be as frictionless as possible, and I worry this might go in the opposite direction.

But as always I'm very willing to be shown that I'm horribly wrong ;-)

**Comment by tdg** [comment]
I definitely don't think we should give them the choice at this stage (if **ever**). Seems the question is whether we _ever_ 'underedact' the name (ie at swap confirmation stage) or _never_ do (in which case it's over to them once they're confirmed. Which is simpler to engineer, and which is more future proof?

**Comment by threedaymonk** [comment]
> on the /user page once partner has confirmed - unredacted

This appears to be `users/show/_swap_confirmed.html.haml`, which is currently unredacted.

> in reminder emails before and on the day of the election - unredacted

This appears to be  `user_mailer/reminder_to_vote.html.haml`, which is currently unredacted.

> in 'I've voted for you' email on the day of the election - unredacted

This appears to be `user_mailer/partner_has_voted.html.haml`, which is currently unredacted.

> (Name) has cancelled swap - unredacted

This appears to be `user_mailer/swap_cancelled.html.haml`, which is currently unredacted.

So can you see why I'm confused?

**Comment by tdg** [comment]
Are any of the mailers redacted? It makes total sense you'd be confused, and might be worth me pointing out the context, which is that redaction is a new feature in the code, so we are still working out where to deploy it…

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 25, 2019 8:30 PM](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-558327064 "2019-11-25T20:30:25Z - Replied by Github Reply Comments"):
> I definitely don't think we should give them the choice at this stage (if **ever**). Seems the question is whether we _ever_ 'underedact' the name (ie at swap confirmation stage) or _never_ do (in which case it's over to them once they're confirmed.

We seem to be going around in circles on this :laughing:  I'm not sure why you see that as a question now?  Because you already provided a sensible approach in [this previous comment](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-557745923) and I see no reason to deviate from that previous plan which still makes perfect sense.

> Which is simpler to engineer

There is zero difference, because there is no (more) engineering required.  @threedaymonk already did the hard work of writing the redaction code (and a superb job it was I might add :wink: ).  Literally all there is to do now is tweak the email and web templates so that they use `.name` or `.redacted_name` in the right places ... and even 90% of this is already did.  I only reported this issue because I spotted a few inconsistencies which needed cleaning up.

So I'm confused why we're having this long discussion now.  Resolving this issue should be stupidly simple. 

> and which is more future proof?

Not sure I understand this question :laughing:

But anyway let's have a chat on the phone about this?  I'm sure we can clear up the confusion quickly.

**Comment by aspiers** [comment]
[**@threedaymonk**](https://github.com/threedaymonk) commented on [November 25, 2019 8:37 PM](https://github.com/swapmyvote/swapmyvote/issues/110#issuecomment-558329647 "2019-11-25T20:37:41Z - Replied by Github Reply Comments"):
> So can you see why I'm confused?

Yes I can, because I'm confused too, and also confused about why we're all confused! :rofl:  I'll try to clear it up with @tdg shortly.
