### ISSUE TITLE
Make swap expiry time configurable 

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#125]
Need to parameterise the swap expiry time via an environment variable.  It is mentioned in the FAQ, a few email and web templates, and also `lib/tasks/swaps.rake`.

**Comment by tdg** [comment]
Can be configured for M0, and parameterised for M1

**Comment by baob** [comment]
@tdg can you please explain what you mean as the difference between 'configure' and 'parameterise' ? I'm thinking they both mean 'make an environment variable that controls this' but they seem to be different things for you.

**Comment by tdg** [comment]
This came out of a conversation with @aspiers and he can probably explain better, but AIUI, we can easily configure it right now, by changing a variable in a file, which is a M0 issue (we want it set to 48 hours for launch)

But I think we want also, for M1, to be able to set it 'within the system' - I guess higher up the stack somewhere

**Comment by aspiers** [comment]
No we want it to be an environment variable from the beginning.

**Comment by baob** [comment]
@aspiers picking this up unless I hear from you that it's already under way

**Comment by aspiers** [comment]
Go for it!

**Comment by baob** [comment]
@aspiers @tdg 
https://github.com/swapmyvote/swapmyvote/pull/180#issuecomment-559493003
