### ISSUE TITLE
Require phone verification before confirming a swap

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#130]
Currently phone verification is entirely optional and has no effect.  We should require it in order to prevent [Sybil attacks](https://en.wikipedia.org/wiki/Sybil_attack).

The right place to enforce the requirement is just as the user has decided a swap partner and is clicking to confirm the swap with that partner, since by then they should be sufficiently invested to be willing to do a tiny bit of extra work.

N.B. We also want to allow verification earlier - it's currently possible via the user's profile page, and via #129 should also become possible just after first login - but this issue is only about the *hard* requirement at the time of swap confirmation.

**Comment by tdg** [comment]
I _think_ the right time to ask is when setting constituency and (for Twitter logins) email. Slightly difficult to check this instinct without the Twitter login path (currently broken)

**Comment by aspiers** [comment]
This one is **SUPER** important.  Any takers?  @threedaymonk or @egglestn or @fkorning  maybe?

**Comment by fkorning** [comment]
How's this: we add 2 fields to mobile_phones. (1) locale cc code, and (2) a randomly generated base 62 OTP activation token.  an activation SMS message is then sent to the mobile number.  it includes a url with the activation code (say ?code=Ghxy17Jfwk90).

**Comment by fkorning** [comment]
or is the activation code already there?  what's the verify_id field? (create_mobile_phones.rb)

**Comment by tdg** [comment]
We already have verifiable phone number (cf https://github.com/swapmyvote/swapmyvote/issues?q=mobile+label%3A%22mobile+verification%22 ) 

- This issue is about making verification mandatory at a **relevant moment** in the user journey.

The latest it could happen is when someone proposes or confirms a swap, respectively. 
The earliest it could happen would be at the same time the user specifies their constituency.

**Comment by aspiers** [comment]
Right, this issue is about the latest time. There is already a separate
issue filed about the earliest time.

**Comment by aspiers** [comment]
Fixed by #187.
