### ISSUE TITLE
Improve phone verification UX

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#131]
We need to improve the text and placement of error messages when wrong or expired verification tokens are entered and a new one gets sent.  Currently the UX is a bit confusing.

**Comment by tdg** [comment]
Current copy (returned by Messagebird) says 
`Failed to verify code to +447700000000: Error code 10: The token is invalid.`
This is high up the page, not near the verify button 

Better would be lower down the page, nearer the entry point eg: 

```**Verifying phone number**
Oh dear, that isn't the right code. 
We have sent you a new 6 digit code - please enter it carefully here:
Verify```

**Comment by tdg** [comment]
If there is the option to **not** automatically send a new code, that would be preferable (so that we don't get bad actors burning through SMS account credit)

If that were the case, copy might read:
```
**Verifying phone number**
Oh dear, that doesn't seem to be right. 
Please re-enter the 6 digit code carefully here:
Verify
```

**Comment by tdg** [comment]
There is already a way to ask for a new code, which works well IMO. Does it have a five minute limit on it (as it suggests)?

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 23, 2019 8:10 PM](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-557829090 "2019-11-23T20:10:25Z - Replied by Github Reply Comments"):
> Current copy (returned by Messagebird) says 
> `Failed to verify code to +447700000000: Error code 10: The token is invalid.`
> This is high up the page, not near the verify button 
> 
> Better would be lower down the page, nearer the entry point eg: 
> 
> ```
> **Verifying phone number**
> Oh dear, that doesn't seem to be right. 
> We have sent you a new 6 digit code - please enter it carefully here:
> Verify
> ```

Agreed, that's much better.

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 23, 2019 8:12 PM](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-557829224 "2019-11-23T20:12:45Z - Replied by Github Reply Comments"):
> If there is the option to **not** automatically send a new code, that would be preferable (so that we don't get bad actors burning through SMS account credit)

There isn't, unfortunately.  It's really a one-time token - if you get it wrong, it gets invalidated immediately so we need to send another one.

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 23, 2019 8:41 PM](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-557831107 "2019-11-23T20:41:49Z - Replied by Github Reply Comments"):
> There is already a way to ask for a new code, which works well IMO. Does it have a five minute limit on it (as it suggests)?

That's part of what #138 is about.

**Comment by stevebaxter** [comment]
I've noticed as well that if you go to the "edit user" page, change the number and hit enter, the verification code gets sent to the old number and the new one isn't saved. Worth looking at as part of this or shall I raise it separately?

**Comment by tdg** [comment]
Good spot and that's probably a separate issue - this one is more about what the user sees and does, whereas that sounds like a bug that could be squashed separately?

**Comment by aspiers** [comment]
Yes that's separate bug, please file a new issue for it.

**Comment by aspiers** [comment]
@baob Did you file a new issue for this? I'm struggling to keep track.

**Comment by stevebaxter** [comment]
@aspiers - do you mean the issue with changing the number? Not yet, I'm about to get on a train so should have some time then!

**Comment by baob** [comment]
> @baob Did you file a new issue for this? I'm struggling to keep track.

I'm not looking at this issue ... should I be ?

**Comment by aspiers** [comment]
@baob Doh sorry wrong person!  That was meant for @stevebaxter ...

**Comment by aspiers** [comment]
[**@Steve Baxter**](https://github.com/Steve Baxter) commented on [November 28, 2019 10:57 AM](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-559446683 "2019-11-28T10:57:37Z - Replied by Github Reply Comments"):
> @aspiers - do you mean the issue with changing the number? Not yet, I'm about to get on a train so should have some time then!

Yes, we need an issue filed for this:

> I've noticed as well that if you go to the "edit user" page, change the number and hit enter, the verification code gets sent to the old number and the new one isn't saved. Worth looking at as part of this or shall I raise it separately?

**Comment by stevebaxter** [comment]
Done - https://github.com/swapmyvote/swapmyvote/issues/193

**Comment by aspiers** [comment]
I'm in the middle of this - finished soon.

**Comment by tdg** [comment]
"Worth mentioning that a new code has been sent. Would have been confusing if the new code was slow to arrive and I'd been trying to reuse the old one" - user feedback

**Comment by aspiers** [comment]
Yes I've already covered that.
