### ISSUE TITLE
Client-side validation of phone number

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#132]
Probably best candidate: [jackocnr/intl-tel-input: A JavaScript plugin for entering and validating international telephone numbers](https://github.com/jackocnr/intl-tel-input)

These also look useful:

- [mobi/telephone_number: Phone number validation for Ruby](https://github.com/mobi/telephone_number)
- [rails/webpacker: Use Webpack to manage app-like JavaScript modules in Rails](https://github.com/rails/webpacker)
- [fnando/normalize_attributes: Sometimes you want to normalize data before saving it to the database like down casing e-mails, removing spaces and so on. This Rails plugin allows you to do so in a simple way.](https://github.com/fnando/normalize_attributes)

**Comment by tdg** [comment]
Given the franchise, would we want to only accept phone numbers from the UK (44), Ireland (353), and Commonwealth countries? Or could that exclude people?

**Comment by tdg** [comment]
Do we need a separate Issue to validate that a phone number is not a duplicate (or another 'spelling eg `+447700000000` & `07700000000`, or will Messagebird pick that up?

**Comment by aspiers** [comment]
> Given the franchise, would we want to only accept phone numbers from the UK (44), Ireland (353), and Commonwealth countries? Or could that exclude people?

No - that would exclude ex-pats.

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 23, 2019 10:25 PM](https://github.com/swapmyvote/swapmyvote/issues/132#issuecomment-557838383 "2019-11-23T22:25:06Z - Replied by Github Reply Comments"):
> Do we need a separate Issue to validate that a phone number is not a duplicate (or another 'spelling eg `+447700000000` & `07700000000`, spaces etc, or will Messagebird pick that up?

Yes good point - filed as #142.
