### ISSUE TITLE
ensure Heroku is running efficient middleware e.g. Puma

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#140]
We don't have a Heroku `Procfile` configured, so I suspect we're running WEBrick in staging and production, which is [the default behaviour for Heroku](https://devcenter.heroku.com/articles/ruby-default-web-server).

If true, that would be *bad* news because that's horribly inefficient, but it would also be *good* news because it would mean that we can get an enormous leap in performance (and consequent reduction in cost) relatively easily:

- https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

@jpallen Do you happen to know either way?

**Comment by aspiers** [comment]
OK I've confirmed from Airbrake stack traces that we're running WEBrick in production.  Oops!!!

**Comment by tdg** [comment]
Ah, good detective work!
