### ISSUE TITLE
Add 'Donate' button 

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#153]
Would be good if this can be top right of the page as this seems standard in the political field
![Screen Shot 2019-11-25 at 19 14 01](https://user-images.githubusercontent.com/95868/69570455-c3679a00-0fb7-11ea-9bf5-840562c7aa1c.png)

This would go live when we go public with our Crowdfunder not before and point to it

![Screen Shot 2019-11-25 at 19 12 40](https://user-images.githubusercontent.com/95868/69570376-9ca96380-0fb7-11ea-9262-2482923a14c9.png)
![Screen Shot 2019-11-25 at 19 12 24](https://user-images.githubusercontent.com/95868/69570377-9d41fa00-0fb7-11ea-956c-f349d41e6324.png)
![Screen Shot 2019-11-25 at 19 12 16](https://user-images.githubusercontent.com/95868/69570378-9d41fa00-0fb7-11ea-9975-437c480c2db9.png)

**Comment by fkorning** [comment]
You mean a "burger" pop-out menu bar in the top right ?   I notice we'include font-awesome glyph icons, whihc means we're already including .js and .css. I coudl add some .css and di something like the following: 

![image](https://user-images.githubusercontent.com/8026632/69893329-c04a1200-1307-11ea-9a92-239f84bd4b41.png)

**Comment by fkorning** [comment]
or with a burger menu:
![image](https://user-images.githubusercontent.com/8026632/69893401-c2f93700-1308-11ea-8839-d936cec9b6dd.png)

**Comment by fkorning** [comment]
or a burger menu:
![image](https://user-images.githubusercontent.com/8026632/69893413-e7edaa00-1308-11ea-995d-dc47a5e2028f.png)

**Comment by tdg** [comment]
I’ve changed the title of the issue to add ‘donate’ button - the original screenshots provided show the same.  

(Support is another way of saying donate)

No menu is needed, and we need to respect and give space for the user profile link and picture in the top right of our page.

**Comment by fkorning** [comment]
@tdg.

I'll need help as all this: ruby, rails, travis, webdev in general (I'm a backend developer) is new to me.

I did as much as I could, rendering a button using an fa-icon , but it doesn't link to a payment system.
 
I forked, did some changes, and submitted a pull request.  for some reason it submitted changes as to my repo as the user 'scentrics-fk' (which is weird, cause that'sthe account for my day-job, even though I'm logged-in as 'fkorning').  but no matter. that's not important. the pull complains about things I know nothing about.  "verification/cla-signed".  Any idea what that is?  also why is the checkstyle so draconian with 80-character lines (so 1980s) ? 

https://github.com/swapmyvote/swapmyvote/pull/219#

**Comment by tdg** [comment]
The button should be a simple link to our crowdfunder, so we  don’t need a payment system @fkorning

**Comment by tdg** [comment]
https://crowdfunder.co.uk/swapmyvote/

**Comment by fkorning** [comment]
done using fa-icon and a css to shrink button size.

![image](https://user-images.githubusercontent.com/8026632/69922782-24e7a700-1497-11ea-9ab5-bd4d58114959.png)

**Comment by tdg** [comment]
Is this done? Can we review/ preview somewhere?

**Comment by fkorning** [comment]
yes,
issue #153: donate button by fkorning · Pull Request #241 · swapmyvote/swapmyvote

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
issue #153: donate button by fkorning · Pull Request #241 · swapmyvote/s...

please ignore false file permissions (weird side-effect of mounting git repo via vm). also ignore Gemfile (had t...
 |

 |

 |






    On Tuesday, 3 December 2019, 17:04:56 GMT, Tom de Grunwald <notifications@github.com> wrote:  
 
 
Is this done? Can we review/ preview somewhere?

**Comment by fkorning** [comment]
https://github.com/swapmyvote/swapmyvote/pull/241#issuecomment-561549320

**Comment by fkorning** [comment]
https://github.com/swapmyvote/swapmyvote/pull/241#issuecomment-561550145

**Comment by fkorning** [comment]
https://github.com/swapmyvote/swapmyvote/pull/241#issuecomment-561550145

**Comment by fkorning** [comment]
greyed icons, capitalised

![image](https://user-images.githubusercontent.com/8026632/70133463-0e4f7480-167e-11ea-96c4-05df77865df6.png)

**Comment by aspiers** [comment]
Addressed in https://github.com/swapmyvote/swapmyvote/commit/20e25f3ca490710c95fc2025afd7e69c840db428
