### ISSUE TITLE
updating user can cause welcome mail to be resent

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#159]
## Problem description

In certain cases when user details are updated, a welcome email gets sent.  Currently this is independent of when the user's `email` field is set, and instead actually dependent on voting preferences and constituency:

https://github.com/swapmyvote/swapmyvote/blob/00b0b176fa6d69b6ab4752c953952a6a29ab326c/app/models/user.rb#L16

https://github.com/swapmyvote/swapmyvote/blob/00b0b176fa6d69b6ab4752c953952a6a29ab326c/app/models/user.rb#L148-L158

We discovered this welcome email code accidentally got triggered while running the `user.update!` in the migration in #143 which populates the `constituency_ons_id` column:

https://github.com/swapmyvote/swapmyvote/pull/143/files#diff-7b8b7e2dcd0b9eafdeccff6b739a1d3eR10

This is because that PR changes the `ready_to_swap?` method to check `constituency_ons_id` rather than `constituency_id`.  So any existing users which have `constituency_id` set but not `constituency_ons_id` prior to the migration would get the latter set by the migration, and that would trigger the email.

## Proposed solution

The `ready_to_swap?` method is a bit of a misnomer as can be seen by its code.  Also it makes more sense to send the welcome email as soon as we get an address, regardless of whether we know their voting preferences or constituency - the latter is not guaranteed, e.g. due to #36.  So @baob and I discussed and think that a more robust approach is:

- Ditch `ready_to_swap?` method.
- Add a new `SentEmail` model which `belongs_to :user` and has a `template` column.
- Every time a welcome email is sent, append a row to this table with the `template` field set to `welcome_email` tracking the delivery.  (Later we can track deliver other emails if we want)
- Replace

https://github.com/swapmyvote/swapmyvote/blob/00b0b176fa6d69b6ab4752c953952a6a29ab326c/app/models/user.rb#L16

with (caution: untested code!)

    after_save :send_welcome_email, if: needs_welcome_email?

    ...

    def needs_welcome_email?
      return !email.blank? && SentEmail.find_by(user: self, template: 'welcome_email')
    end

to ensure that the welcome is only sent to users once, as soon as we have an email for them.

**Comment by aspiers** [comment]
@tdg - @baob and I concluded that this is only an M0 bug if we *don't* wipe the `users` table prior to launch.  If we launch with a blank `users` table then there should be no risk of spamming any user with duplicate welcome emails.

**Comment by tdg** [comment]
> @tdg - @baob and I concluded that this is only an M0 bug if we _don't_ wipe the `users` table prior to launch. If we launch with a blank `users` table then there should be no risk of spamming any user with duplicate welcome emails.

 I think we _should_ flush all users before launch, forcing people to reset and log in again if they want to swap. For a variety of reasons: they may have moved, may have different politics, and we may want to send them back to the start of the process and get them reengaged. We may lose some users like this, but I think we're more likely to have a higher proportion of actual swaps. And we can send a reminder email to 2017 users anyway (from Mailchimp) so not much lost.

Therefore, by the reasoning above, this should be in M1

**Comment by baob** [comment]
Is there an M0 ticket to ensure that the  user table gets flushed ?  ;)

**Comment by tdg** [comment]
There is now! #164
