### ISSUE TITLE
Show tactical recommendations for prospective swap partners

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#161]
Show tactical recommendations for prospective swap partners. 

Bad pen sketches attached of how it could work 
- Polls as they are now (we could add Leave:Remain percentages, then a table for recommendations underneath the person, preferences, and polls).

For the recommendations table I’m seeing it as basically the same as LFB’s, and in order to clarify against voter objectives we could have a further row (underneath) with the overarching objective of the recommendation site (ie leave or remain. If any aren’t clear what their objective is, or are party political, we could note that in grey.).

On mobile, the polls flow down below the person, and the table would flow again beneath that.
There is an argument that this is too much info per voter on mobile, and could either be 1) consolidated or 2) hidden behind a link to ‘expand tactical voting recommendations’. 

![IMG_5802](https://user-images.githubusercontent.com/95868/69675677-17957b80-1097-11ea-8c72-3897e791e50c.JPG)
![IMG_5801](https://user-images.githubusercontent.com/95868/69675678-17957b80-1097-11ea-8064-07a657b94007.jpg)

LFB have horizontal rows per recommendation on mobile:

![Screen Shot 2019-11-25 at 18 45 16 (1)](https://user-images.githubusercontent.com/95868/69675713-2e3bd280-1097-11ea-8288-9212529d6702.png)
![File](https://user-images.githubusercontent.com/95868/69675714-2e3bd280-1097-11ea-9399-4045a833edca.jpg)

**Comment by tdg** [comment]
Suggested data source: caching a version of https://www.livefrombrexit.com/tacticals/data/recommendations.json

Related: #30 (new) and #9 (data updates)

**Comment by aspiers** [comment]
Jesus, and I thought my handwriting was bad :rofl: :rofl: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_winking_eye:

**Comment by baob** [comment]
This commit (since reverted) gives an illustration of how the data might be extracted for use in the user profile template --> https://github.com/swapmyvote/swapmyvote/pull/173/commits/e4dc5950fb16489bd8e470b6550c1f0f6c8f7674#diff-61e61282d82b86bbcc978a6e3909e88fR16

**Comment by baob** [comment]
To get this up and running (and not necessarily looking nice), the only thing need is to add to app/views/user/swaps/_swap_profile.html.haml
```
  %div
    .text-center.small
      Recommendations: #{other_user.constituency.recommendations.count}
    %ul.small
      -other_user.constituency.recommendations.each do |rec|
        %li= link_to "#{rec.site}: #{rec.text}", rec.link
```
The rest is CSS and responsive layout which will no doubt take me (with presently limited FE skillset) some time,

**Comment by tdg** [comment]
Let's update the FAQ with something like:

Q: "What are the tactical recommendations shown"

A: "In order to help you work out whether your vote can help achieve your priorities where your prospective partner votes, we show you recent polls from their constituency, and a list of tactical voting recommendations from different campaigning sites for their constituency. 

These recommendations are aggregated by the website [comparethetacticals.com](comparethetacticals.com) which updates its data every 6 hours to reflect changes in the original sites' recommendations (for example in the light of new polling data), and which we reflect in the site soon afterwards. Each of those sites and their recommendation method is linked to on comparethetacticals.com. 

Given that voters each have different priorities when they cast their vote (and look for a vote swap), also that different campaigns similarly have different priorities, we show all of the sites' recommendations in order to help support you in making your vote count for more, the way you want it to. 

Where the main sites on each different side of the political spectrum agree in their recommendations, this might suggest a consensus behind that recommendation. If there isn't broad agreement, you may wish to read a summary such as [Jon Worth's piece about Remain tactical voting](https://jonworth.eu/2019-uk-general-election-tactical-voting-guide/). We aren't aware of a similar piece on the other side of the political spectrum. 

Please consider this information as advisory, and use it to make your own informed conclusions - and let us know if you find it helpful!
"
