### ISSUE TITLE
/user/edit workflow needs refinement

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#166]
In `/user/edit` (the user's profile editing view), normally the Save button will return back to the normal vote swapping workflow, so the button really means "Save and continue".  However if a mobile phone number is set and needs verification, the Save button will just save any changes to the database but stay on that page in order to give the user a chance to click the Verify button.  In that case the button really means "Save but don't continue".

This is not the most intuitive UI:

1. It means that in the "needs verification" scenario, it's not obvious how to return to vote swapping.
2. It means we have an identical-looking button with two different behaviours.

So it should be improved.  Maybe the ideal UI is to detect the case where the mobile number has just been set, and in that case *only*, offer two separate buttons: "Save" and "Save and continue".

**Comment by stevebaxter** [comment]
Could we just send the code on "Save" if the number is unverified, and take the user to the verification page?

**Comment by aspiers** [comment]
Haha DOH that's much simpler and more elegant isn't it!  Not sure why I thought a verify button was necessary ...  @egglestn I guess this approach might also help streamline your work, but I haven't had a chance to look at what you've done yet.

**Comment by aspiers** [comment]
Please noone work on this without talking to @egglestn and me first.

**Comment by baob** [comment]
See also #636

**Comment by baob** [comment]
@stevebaxter is this on your radar ?

**Comment by baob** [comment]
Need to be careful about the overlap with #625 here ... don't want to be treading on each others toes.

**Comment by baob** [comment]
Relates to #928 ?

**Comment by aspiers** [comment]
And possibly / probably #933 too.

**Comment by aspiers** [comment]
@stevebaxter A long time ago [you came up with this great suggestion](https://github.com/swapmyvote/swapmyvote/issues/166#issuecomment-559479666):

> Could we just send the code on "Save" if the number is unverified, and take the user to the verification page?

Any chance you have time for this later?  It seems to be a common stumbling block still...

**Comment by stevebaxter** [comment]
OK, how about this flow:

https://www.dropbox.com/s/k9b5t1reoi4x8um/Screen%20Recording%202024-07-02%20at%2022.48.44.mov?dl=0

**Comment by stevebaxter** [comment]
The main differences are:

1. Swap the order of the postcode and constituency fields, and make it clear that the postcode is only to find the constituency (this has bugged me for ages)
2. You don't get asked to verify your phone number until the very last moment - when you ask to swap. This is a pain for the user, we want to get them almost to the end of the process (and hooked) before asking for this extra effort.
3. The "Save" and "Verify" buttons are gone from the mobile phone field. It all just happens at the point where you need it to.

Thoughts?
