### ISSUE TITLE
Admin interface for email templates

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#17]
An admin interface for updating the copy in the lifecycle emails (or other contact channels) we use as the election cycle goes on.

**Comment by tdg** [comment]
Depending on which platforms/libraries we use, this may become a non-issue

**Comment by aspiers** [comment]
Yeah, arguably GitHub is already that admin interface since you are already able to edit HAML ;-)

**Comment by aspiers** [comment]
TBH I can't really see a realistic way forward on this, since it's impossible to separate copy from code in the HAML.  Plus @baob already automated a ton of the copy changes between elections, and also GitHub supports editing via web.  So I'm closing but can be reopened if anyone disagrees.
