### ISSUE TITLE
Remove register to vote link on holding page

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#175]
This could be replaced with a support button (precursor to #153 ) pointing at the crowdfunder

**Comment by tdg** [comment]
How about we replace with a 'Help Swap My Vote reach more people' or 'Support our Crowdfunder' link? 

https://crowdfunder.co.uk/swapmyvote/ 

Or shall we put 'Support' under the 'Connect' menu for now, until we can do #153?

**Comment by aspiers** [comment]
Sure! But let's submit separate issues for either/both of those; this one was just about removing the register to vote link.  BTW I was also thinking about adding a link to the contributors guide from under the "Connect" menu - what do you think?

**Comment by tdg** [comment]
Agreed, and can we make the latter simply 'Github' or better 'Our code'?

**Comment by tdg** [comment]
Or even: 'Contribute' - perhaps your suggestion was better
