### ISSUE TITLE
Add link to GitHub project from footer?

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#185]
We could create a link to the GitHub project (probably the contributor's guide) from the Connect section of the web footer.  It probably shouldn't be called "Contribute" because our main audience is non-techie and would confuse that with donations etc. (which we need to do separately anyway).  Maybe "Community" is also not clear enough that it relates to technical contributions.  "Get involved" is the best I can think of right now.

Alternatively rather than linking directly to GitHub, it could link to a new static page which explains different ways (technical *and* non-technical) people can help the project.

**Comment by tdg** [comment]
>Alternatively rather than linking directly to GitHub, it could link to a new static page which explains different ways (technical and non-technical) people can help the project.

That's a really good idea

**Comment by aspiers** [comment]
Resolving in favour of #303.
