### ISSUE TITLE
Clicking "Verify" doesn't use updated phone number

### ISSUE THREAD

**Issue by stevebaxter** [swapmyvote/swapmyvote#193]
On the user "edit" page:

1. Enter a phone number and save
2. Type a different number and click "Verify" or hit the enter key
3. The verification code will be sent to the original number, not the new one

We should probably submit the form before sending the verification code?

**Comment by aspiers** [comment]
When this is fixed, need to let this user know https://twitter.com/deanjane55/status/1202525304360775680

**Comment by aspiers** [comment]
@egglestn Any chance you could look at this?

**Comment by aspiers** [comment]
or @stevebaxter :-)

**Comment by aspiers** [comment]
Fixed by #323
