### ISSUE TITLE
Establish way of recording consent for login email address to be sent news

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#195]
We need to establish a method of recording consent for using the user’s login email address to contact them for news and other purposes (from Forward Democracy). This needs to be opt in.

This might take the form of a check box at the point that we take their email address confirming (copy to be decided). It needs to create a record in the backend indicating the user has opted in (and ideally a timestamp and URL).

Note: we already have tracking of consent to be emailed by swap partners, but that is a different thing (see #345).

**Comment by tdg** [comment]
Without this, it may be hard to justify contacting our users other than for the use of the app, which would be deleterious to our wider aims of promoting and defending democracy.

**Comment by tdg** [comment]
@aspiers can we make this M0?

**Comment by tdg** [comment]
Agreed to approach this in a different way
Proposal that a returning visitor could be presented with a full page modal offering updates 
(on democracy tools, electoral reform, tech for good, etc). They would have to opt in or opt out to move forward with their journey.

**Comment by tdg** [comment]
We should record a timestamp for consent

**Comment by aspiers** [comment]
We may not have time to do this before GE, is that a big problem?

**Comment by aspiers** [comment]
Agreed it might be a lost opportunity but technically the privacy policy does allow us to do this and also we can get more explicit consent post-GE in other ways.

**Comment by joshr** [comment]
concurring with the need for this, we should have a checkbox for opt-in consent for the newsletter.

i can provide encouraging wording.

**Comment by aspiers** [comment]
@joshr @tdg Is this *purely* about consent for news, or is it about consent in general?  Because we also have a mechanism for obtaining consent to be emailed by swap partners, for which there is a refinement suggested in #345.

**Comment by tdg** [comment]
It's purely about newsletter type contact. I suspect that down the line we might be able to streamline collecting and recording the two consents, but for now doing them separately would meet the project need.

**Comment by aspiers** [comment]
Updated title and description to clarify that this is about the login email, not the email they enter into the newsletter signup form.
