### ISSUE TITLE
address foreign phones

### ISSUE THREAD

**Issue by fkorning** [swapmyvote/swapmyvote#199]
The phone won't necessarly be GB for +44.  For example I live in London but still use a French mobile in +33.  Also, UK citizens living abroad may have foreign mobiles (sounds like a huge can of worms)

Phone parsing and validation using mobil requires knowning the locale (iso 2-letter country code).
add this field to the dao.  We can address rules for residence later-on, but we should at minimum persist the country code.

**Comment by aspiers** [comment]
I'm afraid I don't understand this.  We're well aware that some voters will have foreign numbers, and AFAICS the app currently supports foreign numbers fine.  Please can you describe the exact steps you are taking in the app to reproduce the issue, and what the expected behaviour should be?

**Comment by fkorning** [comment]
it's not a bug, it's a feature request.  but since you're telling me the app already supports foreign numbers, you can skip this.  I'd just like to persist the country code in db, in case one wants to do further phone manipulations later-on...

**Comment by aspiers** [comment]
The country code is persisted in the db already.
