### ISSUE TITLE
Validate leading zero on phone number

### ISSUE THREAD

**Issue by jpallen** [swapmyvote/swapmyvote#209]
At the moment, if you enter a phone number with no leading zero, the system accepts it and won't show any errors. It also claims to have sent a verification message, but no comes through.

We should either reject the input of a number with no leading zero (do we need to check other properties of a valid phone number too?), or automatically prepend the leading zero if needed.

**Comment by jpallen** [comment]
(As a very quick fix we could just add some text to say to include the leading zero)

**Comment by tdg** [comment]
Bearing in mind phone numbers always work with country codes, but can _not_ work without, it might be better to _not_ accept and not store the zero. 

This would also be more future proof ( #43 )

Having the (0) visible so that the user doesn't need and can't type it would be a useful UX pattern

**Comment by aspiers** [comment]
The phone number normalisation is done by a library, not by us, so we probably don't get to choose how it is stored unless that library has options.  @stevebaxter please can you look at this?

**Comment by stevebaxter** [comment]
This is working for me - if I enter my number without the leading 0, it's stored as +447730xxxxxx and the text gets sent. Are you possibly changing the number and clicking "Validate" or hitting enter straight away? There is another bug where the number isn't saved before validation in that scenario.

**Comment by stevebaxter** [comment]
If there is anything else you can provide for me to repro that would be good?

**Comment by jpallen** [comment]
@stevebaxter 

It seems if I enter my phone number without a leading zero for the first time, it saves it in the database as '7500640263'. But it gets cast to have a leading zero when displayed, but not when sending the code? See screencast below:

![phone problems](http://g.recordit.co/QK9tZ72hS6.gif)

**Comment by stevebaxter** [comment]
OK, let me see what's going on here

**Comment by stevebaxter** [comment]
Ah there's a second save button!!

**Comment by aspiers** [comment]
Yeah we need to fix that.  Not good UI.

**Comment by stevebaxter** [comment]
I think this is a problem in #187. We need to make sure we get the canonicalised phone number from the hidden input.

**Comment by stevebaxter** [comment]
I think we need to fix this before merging #187 :

https://github.com/swapmyvote/swapmyvote/pull/187#discussion_r352215727

This can then be closed as it shouldn't be an issue anymore.

**Comment by aspiers** [comment]
OK applying that tweak.  I'll test but not 100% sure how to test, @stevebaxter did you already test it?
