### ISSUE TITLE
Tactical campaigns need renaming

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#229]
@tdg has requested:

* could we name the sites with Names like GetVoting, Remain United,
* is it possible easily to swap the order of the two tacticalvote sites so that .co.uk comes first?

I think it makes sense to understand what other supplementary info about the recommendation _sites_ we need to display and work on it together. Obviously from the above we need

* SMV-standardised name
* Sort order 

Do we need a colour code too ?  What about remain versus leave ? 

[This PR](https://github.com/swapmyvote/swapmyvote/pull/227) needs to be merged before this issue can be completed, but it can be started at any time.

**Comment by aspiers** [comment]
Please discuss with @tdg if possible to refine this card into concrete actions. I recommend splitting into multiple issues (e.g. colour and remain vs. leave seem separate to me).

**Comment by baob** [comment]
Some of this info is in the json, just not extracted yet
```
    {
      "siteName": "GetVoting",
      "siteUrl": "https://getvoting.org",
      "site": "get-voting",
      "features": [
        "<strong>Stop Brexit</strong>",
        "By <a href=\"https://www.bestforbritain.org/\" target=\"_new\">Best for Britain</a>",
        "Method <a href=\"https://getvoting.org/faq.html\" target=\"_new\">MRP</a>"
      ]
    },
```

**Comment by baob** [comment]
And @aspiers asked for 

> Actually we should seriously consider displaying "last updated at ..." somewhere

**Comment by aspiers** [comment]
@baob Not relevant for BE2021 but didn't we (well, you) complete this?  Or is it kept open because we didn't implement the "last updated at..." suggestion?

**Comment by baob** [comment]
Natural follow-on when the PR for issue #773 gets merged. It will largely revolve around adding more data to the recommendations helper, then using that in the view.

@aspiers we were talking about this on Sunday afternoon.

**Comment by baob** [comment]
@tgd @aspiers Can you give me an agreed list of 'campaign names' to replace the domain names please ?

I'll make myself busy adding meta descriptions from the campaigns websites for use as mouse hovers, or whatever.

**Comment by baob** [comment]
> * could we name the sites with Names like GetVoting, Remain United,

@aspiers @tdg  Is this still important ?

**Comment by aspiers** [comment]
I wouldn't say _super_ important - presumably presenting the TV campaign names according to their chosen branding is more cosmetic than anything else ... but isn't it also extremely quick easy to do?

**Comment by tdg** [comment]
Stop The Tories 
Get Voting
Tactical Vote UK
Tactical (dot) Vote
Scotland in Union
Sprint for PR

**Comment by tdg** [comment]
Can they please _not_ be live links to the sites in question. 

I'd like to have a page on the site where we have info about and links to all TV sites, so they could potentially all link to that page (tbc) instead?

**Comment by aspiers** [comment]
Don't have a strong opinion here but I am curious about the rationale for this request :)

**Comment by baob** [comment]
For me, having a link to the TV site is a way of validating that we're using an external source and not just making stuff up. If we remove the link, I feel we should have a link at least at the bottom of the page to some new page with a description and link. 

At the moment I favour keeping the link with two possible enhancements:
* take the meta description from each site, and use that as alt text (viewable as mouse over) on the link
* make the links launch in a new window/tab so they don't lose the swapmyvote page.

**Comment by baob** [comment]
> I'd like to have a page on the site where we have info about and links to all TV sites, so they could potentially all link to that page (tbc) instead?

If we're doing that, can we make it a separate change and unlink at that point?

Someone needs to draft that page, I'm not sure what degree of explanation is needed?

**Comment by tdg** [comment]
> If we're doing that, can we make it a separate change and unlink at that point?

For sure

**Comment by tdg** [comment]
For now, the two enhancements would be great, especially 
> make the links launch in a new window/tab so they don't lose the swapmyvote page.

**Comment by tdg** [comment]
Rationale being that the current links - multiple on the page even to the same site, give a lot of prominence. Links are calls to action as well as reference point, the former isn't needed (while of course the reference function is)

**Comment by baob** [comment]
Now that PR #851 and #863 have been merged, everything remaining is now covered by issue #850 I think.
