### ISSUE TITLE
Four parties in one recommendation

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#232]
This json comes from livefrombrexit
```
"recs": [
                {
                    "link": "https://tacticalvote.getvoting.org/lanark-and-hamilton-east/",
                    "recommendation": "Green\nLab\nLibDem\nSNP",
                    "site": "get-voting"
                },
```
The display in our tactical recommendations section can look awful in the desktop (vs mobile) rendering.

**Comment by aspiers** [comment]
Not only that, but the same JSON can render on the BFB site as totally different recommendations:

https://tacticalvote.getvoting.org/lanark-and-hamilton-east/ says SNP

https://tacticalvote.getvoting.org/linlithgow-and-east-falkirk/ says "any remain"

This is either a bug with BFB's export, or with how LFB are importing/scraping.  In either case we need to talk to the appropriate contact.  Maybe @tdg can help here.

**Comment by tdg** [comment]
>Maybe @tdg can help here.
Have reached out

**Comment by tdg** [comment]
> This is either a bug with BFB's export, or with how LFB are importing/scraping. In either case we need to talk to the appropriate contact. Maybe @tdg can help here.

Is it possible this will be fixed by #238 ?

For the record, BFB say:
_We have made specific recommendations in some Scottish constituencies where it is possible the Conservatives could win. It is vital we vote for candidates who can stop the Tories. However, in other constituencies we have avoided giving specific advice as it is clear that pro-Europeans are likely to win regardless and we do not believe it would be helpful or desirable for us to attempt to choose between parties who are our allies in the fight against Brexit._
https://tacticalvote.getvoting.org/FAQs/

**Comment by indeox** [comment]
Hi team! @tdg, got in touch about this. Happy to help as best I can.

Yes, indeed GetVoting updated a bunch of recommendations over the last few days, resulting in some of their Scottish "multi-choice" fields changing to *SNP*. The latest feed should reflect that.

Other things I didn't expect:
- Sites suggesting multiple parties to vote for (You noticed this comes down as a string with linebreaks , purely not to break too many things, but if it's better for you, I can send down an additional field as an array if you like... `recommendationList: ["Green", "Lab", "Lib Dem", "SNP"]`)
- Sites rebranding completely, moving lock-stock-and-barrel to a new domain and/or removing/restructuring their feeds entirely (ie: both GetVoting and TacticalBrexit did this)

I do apologise for not having consistent naming for parties. This was made worse when some sites removed their JSON feeds and had to switch to scraping - where they ended up having a different naming convention between their feed and their webpage. It was a stupid shortcoming I should have dealt with early on 😞 

So if you let me know which fields are giving you grief, I'll do my best to help out.

**Comment by aspiers** [comment]
Thanks so much David!

**Comment by baob** [comment]
Ooops ... another special case to deal with:
![image](https://user-images.githubusercontent.com/55932/70221846-f7be2180-1740-11ea-9fc2-ce6c60c71cca.png)

**Comment by baob** [comment]
> * Sites suggesting multiple parties to vote for (You noticed this comes down as a string with linebreaks , purely not to break too many things, but if it's better for you, I can send down an additional field as an array if you like... `recommendationList: ["Green", "Lab", "Lib Dem", "SNP"]`)

Hi @indeox 

If you can do that without too much effort, that would be appreciated. It might make our lives a little easier when we  get to this problem. Don't bust a gut for it though ... if we know that you're consistently using line feeds for multiple parties, that's almost as easy ... however, see the example above, where the word "or" is the separator (may be line feeds too, didn't check the json yet).

**Comment by baob** [comment]
@aspiers @tdg We can probably close this as it doesn't look like we'll be importing this data again.

**Comment by tdg** [comment]
At least not this time I think

**Comment by baob** [comment]
Next time may be 5 more years away, and in that elapsed time I _think_ the data will have then changed, and this problem disappeared.
