### ISSUE TITLE
Monitor email deliverability of production environment via Mailgun

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#235]
This is a sister issue for #40 - the latter covers the staging environment whereas this is for the live site.

Currently we don't have much mileage testing email deliverability for the 2019 launch.  This is a concern, so this issue is about keeping a close eye on things in the first week of launch especially.

https://app.mailgun.com/app/sending/domains/mail.swapmyvote.uk/logs is the place to monitor this for production (log into Heroku swapmyvote first then follow link to Mailgun).

See also #182 where we previously had the production site misconfigured to use a sandbox subdomain (probably an intentional leftover from 2017).

**Comment by aspiers** [comment]
For example it gets a bounce when sending to me - this greatly worries me:

```
{
	"severity": "permanent",
	"tags": [],
	"storage": {
		"url": "https://sw.api.mailgun.net/v3/domains/mail.swapmyvote.uk/messages/AgEFnbXDZ7FdP_JI6OtE_It4m1WCl8AbZA==",
		"key": "AgEFnbXDZ7FdP_JI6OtE_It4m1WCl8AbZA=="
	},
	"delivery-status": {
		"tls": true,
		"mx-host": "mail.adamspiers.org",
		"code": 450,
		"description": "",
		"session-seconds": 2.749601125717163,
		"attempt-no": 1,
		"message": "4.1.8 <bounce+6414e4.ee93b-twitter=adamspiers.org@mail.swapmyvote.uk>: Sender address rejected: Domain not found"
	},
	"recipient-domain": "adamspiers.org",
	"id": "3EJciYRuTEa21UAVwGoc1w",
	"campaigns": [],
	"reason": "generic",
	"user-variables": {},
	"flags": {
		"is-routed": false,
		"is-authenticated": true,
		"is-system-test": false,
		"is-test-mode": false
	},
	"log-level": "error",
	"timestamp": 1575237269.697557,
	"envelope": {
		"transport": "smtp",
		"sender": "hello@swapmyvote.uk",
		"sending-ip": "209.61.151.243",
		"targets": "twitter@adamspiers.org"
	},
	"message": {
		"headers": {
			"to": "twitter@adamspiers.org",
			"message-id": "5de4368f67468_42b19b1c8c6fc80721@15ba8ea6-5100-4a2a-8b47-45fafb22a3ab.mail",
			"from": "Swap My Vote <hello@swapmyvote.uk>",
			"subject": "Welcome to Swap My Vote"
		},
		"attachments": [],
		"size": 4979
	},
	"recipient": "twitter@adamspiers.org",
	"event": "failed"
}
```

**Comment by tdg** [comment]
`"message": "4.1.8 <bounce+6414e4.ee93b-twitter=adamspiers.org@mail.swapmyvote.uk>: Sender address rejected: Domain not found"`

We have SPF/TXT DNS entry for `mail` set to `v=spf1 include:mailgun.org ~all`

**Comment by tdg** [comment]
And another one for `smtp._domainkey.mail` to `k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwJvKzadrCThoKizYD+Szr9KUBJ6FHkRFHrPuGkVfA0cFErFvtgPJZPvZxJa9XJ8cC1ALDKaMI3z5RPPycfjNirgmvlav5ZnhOF+/c/2qQcw10+oVlb04QPiL3RD4Ldfo5ZkedKHfgq6feFFHAZIxvzEtKGI1FLabJnRKtS9UjhwIDAQAB`

(Please delete/edit this comment if need be - just putting here in case it helps expedite the solution)

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [December 2, 2019 2:11 AM](https://github.com/swapmyvote/swapmyvote/issues/235#issuecomment-560166077 "2019-12-01T22:11:25Z - Replied by Github Reply Comments"):
> `"message": "4.1.8 <bounce+6414e4.ee93b-twitter=adamspiers.org@mail.swapmyvote.uk>: Sender address rejected: Domain not found"`
> 
> We have SPF/TXT DNS entry for `mail` set to `v=spf1 include:mailgun.org ~all`

Yes, I really wonder why it doesn't have `a` `mx` or `include:swapmyvote.uk` (possibly because Mailgun didn't recommend this which is weird).  I've added `a mx` to SPF for both `mail` and `staging` so let's see if that helps.

**Comment by aspiers** [comment]
@tdg Just checked again - almost 98% deliverability!  Let's check this every few days.

**Comment by aspiers** [comment]
Actually, I think we can close this - seems very unlikely email deliverability would suddenly break now.  But we should still check every now and then.
