### ISSUE TITLE
Add stronger CTA on swap selection page

### ISSUE THREAD

**Issue by jt-nti** [swapmyvote/swapmyvote#236]
When choosing which user to swap with, there's a list of 'cards' displaying user details, polling data etc., but there's no positive call to action.

It would be nice to make it explicit what is going on, i.e. selecting someone to swap votes with. E.g.

- “Swap with Donna P”? somewhere/top left, possibly as a button
- an “Ask to Swap My Vote” button underneath all the swap detail (note: need to think about how this would sound on a screen reader- lots of identical buttons being read out would be bad)

**Comment by tdg** [comment]
Alternative would be to have 'click the profile with whom you'd like to propose a swap' hovering at the top of the page, or similar

Or 'click to swap'

**Comment by baob** [comment]
Definitely needs *something* ... it's vague as it stands.

**Comment by stevebaxter** [comment]
It's also a bit of a problem for touch devices as it stands - there's a hover effect when you use the mouse, but you won't see that for a phone or tablet. A positive button would be good I think.

**Comment by aspiers** [comment]
I think it would be enough to have a button which just says "Swap".

**Comment by tdg** [comment]
Agree

**Comment by baob** [comment]
@stevebaxter Any interest in picking this up again ? Assuming it's generally thought to be a priority of course .... @tdg ? @aspiers ?

**Comment by stevebaxter** [comment]
Yep can do this next. I think we need a button, the hover behaviour isn't great.

**Comment by stevebaxter** [comment]
How about this?

![Screenshot 2024-06-10 at 23 24 15](https://github.com/swapmyvote/swapmyvote/assets/5228091/5c180d9d-c0da-4e2a-b3a6-299d76795b18)

**Comment by stevebaxter** [comment]
Mobile view:

![Screenshot 2024-06-10 at 23 24 39](https://github.com/swapmyvote/swapmyvote/assets/5228091/1d7b0407-b916-4bd8-b65c-691ff7321829)

**Comment by baob** [comment]
You should probably also check what it looks like with the polls and recommendations also showing. If you run

    ELECTION_TYPE=g rake db:seed
    
those will show up.

**Comment by stevebaxter** [comment]
Here's how it looks with polls and recommendations:
<img width="1822" alt="Screenshot 2024-06-12 at 00 57 43" src="https://github.com/swapmyvote/swapmyvote/assets/5228091/0b57d334-edf2-4e82-800c-8a306b1a7a90">

**Comment by tdg** [comment]
Amazing - thank you!

Would it be worth going with either ‘Swap My Vote’ or ‘Swap with me’? Partly it might be useful to be a bigger button, and partly for consistency (in the first case that is)

**Comment by tdg** [comment]
I also think it might benefit from being centred rather than right justified, appear more compelling

**Comment by stevebaxter** [comment]
@tdg how about this:
![Screenshot 2024-06-13 at 19 47 24](https://github.com/swapmyvote/swapmyvote/assets/5228091/d2006ad6-0f83-4380-a941-fac150bfdead)

**Comment by tdg** [comment]
That looks fantastic - things coming together! 

Wondering if 'Swap with me' works better as a CTA - any thoughts?

**Comment by stevebaxter** [comment]
I think it works either way, happy to change to whichever you would prefer?

**Comment by tdg** [comment]
Or 'Offer to swap' - might be more accurate a CTA?

**Comment by stevebaxter** [comment]
"Ask to swap"?

**Comment by tdg** [comment]
Perfect
