### ISSUE TITLE
Put consent up above all login option buttons

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#244]
when we next revisit (once email login is integrated)

**Comment by tdg** [comment]
Related: #15 #243 #237 #216

**Comment by aspiers** [comment]
Why is this needed? Is it really urgent?

**Comment by aspiers** [comment]
@tdg

**Comment by aspiers** [comment]
@tdg Please can you update the title and description to clarify what type of consent this is about, and how it relates to the other consent issues we have? It's getting quite confusing with all the different nuances!

**Comment by tdg** [comment]
I don't see this as relevant any more, we seem to record consent effectively

**Comment by aspiers** [comment]
Yeah think you're right.  Closing.
