### ISSUE TITLE
[Airbrake] [Production] 535 5.7.0 Mailgun is not loving your login or password

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#250]
**Airbrake error:** [#9565](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/2625650868546149565)
**Airbrake project:** swapmyvote

**Error type:** `Net::SMTPAuthenticationError`
**Error message:** `` 535 5.7.0 Mailgun is not loving your login or password ``
**Where:** `sessions#create`
**Occurred at:** Dec 02, 2019 16:59:33 UTC
**First seen at:** Dec 02, 2019 16:59:33 UTC
**Occurrences:** 0 (0 since last deploy on Dec 02, 2019 16:59:10 UTC)
**Severity:** `error`

**URL:** [https://www.swapmyvote.uk/auth/twitter/callback?oauth_token=8P2RRgAAAAABA2j8AAABbseNg84&oauth_verifier=T36GxqK4L4uz2hSpAFPgatKFyJINPGy7](https://www.swapmyvote.uk/auth/twitter/callback?oauth_token=8P2RRgAAAAABA2j8AAABbseNg84&oauth_verifier=T36GxqK4L4uz2hSpAFPgatKFyJINPGy7)
**File:** `/PROJECT_ROOT/vendor/ruby-2.6.5/lib/ruby/2.6.0/net/smtp.rb`

**Backtrace:**
```
/PROJECT_ROOT/vendor/ruby-2.6.5/lib/ruby/2.6.0/net/smtp.rb:981:in check_auth_response
/PROJECT_ROOT/vendor/ruby-2.6.5/lib/ruby/2.6.0/net/smtp.rb:736:in auth_plain
/PROJECT_ROOT/vendor/ruby-2.6.5/lib/ruby/2.6.0/net/smtp.rb:728:in authenticate
/PROJECT_ROOT/vendor/ruby-2.6.5/lib/ruby/2.6.0/net/smtp.rb:565:in do_start
```

**Comment by jpallen** [comment]
Was temporary issue while I changed credentials
