### ISSUE TITLE
Fit consent and login options notes on one mobile page 

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#257]
"Can’t scroll to the bottom of the login popup on iPhone Safari, iPhone Chrome or iPhone Facebook browser. (iPhone 6s, iOS 13.1.3). I’ll do it on my PC because I’m a big believer in this and want to participate - but I fear you will lose a lot of takers because of this!"

![78039185_10158044551275774_5239642685580509184_n](https://user-images.githubusercontent.com/95868/70007149-3ac49d00-1567-11ea-80ee-f04d96e67864.jpg)

**Comment by tdg** [comment]
Suggested copy change in **bold** below (_italics_: no change)

_- [ ]  I consent to SwapMyVote processing my personal data

We will share your voting preferences and the public link to your Facebook or Twitter account with your swaps, once confirmed, so they know who you are. We may send this information by email or text message.

We will never share anything with anyone else or post to your feed without your permission._

**We're introducing log in with email. We're waiting for approval to reintroduce log in with Facebook. For now, please log in with Twitter.**

Why do I need to log in with Twitter?

**Comment by aspiers** [comment]
Shrink the font size!! At least on mobile

**Comment by baob** [comment]
Not the same issue any more with 'waiting for facebook' now gone, but still needs addressing
