### ISSUE TITLE
Add constituency to API

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#26]
To allow third party sites to populate constituency as well as _preferred_ and _willing_ parties

**Comment by aspiers** [comment]
@tdg Please can you clarify this one?

**Comment by tdg** [comment]
This would mean that a third party site could call a swapmyvote page with constituency (or postcode) autofilled, as they can with `preferred_party` and `willing_party`

**Comment by aspiers** [comment]
@tdg What do you mean by "call a swapmyvote page" here?  Do you mean a hyperlink / redirect, or embedding a swapmyvote page, or just calling the backend API and bypassing the swapmyvote frontend altogether?

Also I'm not yet familiar enough with the site to know what this means:

> as they can with `preferred_party` and `willing_party`

**Comment by tdg** [comment]
Reference: http://bit.ly/swapmyvote-api

**Comment by tdg** [comment]
The doc needs revision, but the idea is that a site ca pre-populate those fields that a user can choose - preferred and willing party choices. But it would help to add constuency to them (postcode if we go down the postcode route with the platform)

**Comment by aspiers** [comment]
OK, but it redirects to a normal page on swapmyvote.uk right?  So it's not a typical API where two machines talk via (say) JSON over HTTP without any frontend, but rather just a way of prepopulating responses to part of the existing frontend?  Just making sure I understand correctly.

**Comment by tdg** [comment]
That's right. I don't _think_ that would change in the event that we produce an #20 embeddable widget, but seems worth mentioning here. 

Clearly I would think we can't serve actual voter data to a third party site, so the API is bound by that
