### ISSUE TITLE
[Airbrake] [Production] undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#262]
**Airbrake error:** [#8468](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/2626462807224458468)
**Airbrake project:** swapmyvote

**Error type:** `ActionView::Template::Error`
**Error message:** `` undefined method `name' for nil:NilClass ``
**Where:** `swaps#new`
**Occurred at:** Dec 03, 2019 19:52:44 UTC
**First seen at:** Dec 03, 2019 19:52:44 UTC
**Occurrences:** 0 (0 since last deploy on Dec 03, 2019 13:06:52 UTC)
**Severity:** `error`

**URL:** [https://www.swapmyvote.uk/user/swap/new?user_id=23466](https://www.swapmyvote.uk/user/swap/new?user_id=23466)
**File:** `/PROJECT_ROOT/app/views/user/swaps/_double_check_constituency.html.haml`

**Backtrace:**
```
/PROJECT_ROOT/app/views/user/swaps/_double_check_constituency.html.haml:8:in _app_views_user_swaps__double_check_constituency_html_haml__61931362430992634_47028162713100
/GEM_ROOT/gems/actionview-5.2.3/lib/action_view/template.rb:159:in block in render
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in instrument
/GEM_ROOT/gems/actionview-5.2.3/lib/action_view/template.rb:354:in instrument_render_template
...
Caused by NoMethodError: undefined method `name' for nil:NilClass
```

**Comment by egglestn** [comment]
Possible fix: https://github.com/swapmyvote/swapmyvote/pull/268

**Comment by egglestn** [comment]
https://github.com/swapmyvote/swapmyvote/pull/270 has a belt and braces fix so the partial doesn't break.

Presumably, if you get here, your swap partner has gone away, so there is a case for a more structural check
