### ISSUE TITLE
[Airbrake] [Production] undefined method `email' for nil:NilClass

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#266]
**Airbrake error:** [#7995](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/2626851525378677995)
**Airbrake project:** swapmyvote

**Error type:** `NoMethodError`
**Error message:** `` undefined method `email' for nil:NilClass ``
**Where:** `users#update`
**Occurred at:** Dec 04, 2019 08:45:03 UTC
**First seen at:** Dec 04, 2019 08:45:03 UTC
**Occurrences:** 0 (0 since last deploy on Dec 03, 2019 21:12:34 UTC)
**Severity:** `error`

**URL:** [https://www.swapmyvote.uk/user](https://www.swapmyvote.uk/user)
**File:** `/PROJECT_ROOT/app/mailers/user_mailer.rb`

**Backtrace:**
```
/PROJECT_ROOT/app/mailers/user_mailer.rb:28:in swap_cancelled
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in block in process_action
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in run_callbacks
```

**Comment by egglestn** [comment]
Should be fixed by https://github.com/swapmyvote/swapmyvote/commit/ad3658d5c8d0248d78cc6a02af2fd0d51b6c6a87, suggest we close and only reopen if it appears again

**Comment by egglestn** [comment]
Possible fix: https://github.com/swapmyvote/swapmyvote/pull/268

**Comment by aspiers** [comment]
This is totally weird - the backtraces are showing a case where a chosen user with an incoming swap has the corresponding `user.incoming_swap.choosing_user` as `nil`, so it bombs when it tries to email the choosing user.

However swaps are being cancelled fine (modulo some minor mess described in #186).  So I don't know how we are ending up with a situation where there is a chosen user but no choosing user.  @jpallen Any ideas?

In any case I guess #268 should handle it correctly now.

**Comment by aspiers** [comment]
The following finds 11 users with this problem:

```
Swap.joins(:chosen_user).left_outer_joins(:choosing_user).where(choosing_users_swaps: {id: nil})
```

I have no clue how they're getting like that though.  We can't even detect this by adding a foreign key constraint because the problem is records in `swaps` where the `id` is not referenced by any `swap_id` in the `users` table.

See also the docs at https://github.com/swapmyvote/swapmyvote/blob/master/doc/db-schema.md:

![`User` / `Swap` assocation](https://g.gravizo.com/source/svg?https://raw.githubusercontent.com/swapmyvote/swapmyvote/master/doc/user-swap-schema.plantuml)

**Comment by aspiers** [comment]
Worked around in #268, and filed #288 as the underlying bug.
