### ISSUE TITLE
Add identity verification icons for potential swap partners

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#28]
When presenting the list of swap candidates, we should put little icons beside each candidate showing how they've verified their identity so far, and by implication (maybe later even explicitly) how much trust can be placed in that candidate being a real person.

**Comment by aspiers** [comment]
This cannot be done until #44 is implemented.

**Comment by tdg** [comment]
We can just use tiny fontawesome icons for mobile, email, facebook, and twitter

**Comment by tdg** [comment]
Can we also show it to the user themselves (about themself) - nice little nudge

**Comment by tdg** [comment]
with title="This user has provided an email" on the HTML element providing useful tooltips on hover
title="This user verified their mobile phone number"
title="This user has a valid Facebook account"

**Comment by jt-nti** [comment]
As far as I understand it, a swap candidate cannot accept a swap until they have verified a phone number. They will definitely have a valid twitter or Facebook (when facebook works) account, to have got in the system, so it seems like it's worth drawing attention to. Maybe even listing unverified accounts below people who are ready to swap.

**Comment by aspiers** [comment]
[**@aspiers**](https://github.com/aspiers) commented on [November 28, 2019 7:13 PM](https://github.com/swapmyvote/swapmyvote/issues/28#issuecomment-559529585 "2019-11-28T15:13:24Z - Replied by Github Reply Comments"):
> This cannot be done until #44 is implemented.

This is not true - I was confused ;-)  We already allow users to verify mobile, and logging in via Twitter or Facebook are forms of identity verification.  The only thing which depends on #44 is being able to display *both* Facebook and Twitter icons on a single user profile.

I think this is very easy to implement and worth doing ASAP -> moving to M2.

**Comment by aspiers** [comment]
Closed by #325.
