### ISSUE TITLE
Point people to their polling station, at the end of the user journey

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#29]
![Screen Shot 2019-10-31 at 20 00 29](https://user-images.githubusercontent.com/95868/67982057-db970400-fc19-11e9-9a48-aa508cfa8ddc.png)
Tactical Vote do this nicely, with a link to https://wheredoivote.co.uk/ using the user's postcode (which they will hopefully have supplied)

**Comment by aspiers** [comment]
@tdg Please clarify exactly where you want this to appear?

**Comment by tdg** [comment]
I think this should be on voters user page when their swap has been confirmed.

"Now that you've confirmed your swap"…
 _you can reach out to your voting partner, establish trust etc…_
"and make sure you know where to vote - find your local polling station here" https://wheredoivote.co.uk/

**Comment by aspiers** [comment]
OK so basically in this web page template:

https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user/vote/show.html.haml

but presumably also this email template:

https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user_mailer/swap_confirmed.html.haml

Neither require anything other than basic knowledge of HTML and HAML, so I'll take the liberty of assigning to you ;-)  Can you submit a PR at some point?  Ping me if you need help.

**Comment by tdg** [comment]
Possible other places: 
- the confirmed swap email, 
- the final, not-confirmed swap email
- the 'tell your partner you've voted' email
