### ISSUE TITLE
write to all swappers who haven't yet given consent to share email address (#281)

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#298]
We need to write to all ~~confirmed~~ swap partners ~~whose Facebook public link isn’t working~~ ~~who registered via Facebook~~ who haven't yet given consent to share their email address with their partner, to get them to give consent.  Contributes to fixing #281.

**Comment by tdg** [comment]
We also need to think about what to do with all those that haven’t confirmed or proposed, when they do. 

Can we flag up to them in the system somehow. Ugh.

**Comment by baob** [comment]
Don't understand the scope here ... do we just produce a list of email addresses as a one off (for someone else to email) ?  Or is it more a case of a facility for ad hoc mailouts to anyone fitting the criteria. ? 

And what is the criteria ?  That someone has reported the profile ? or do we need to do an automated detection ?

**Comment by baob** [comment]
Note: relates to https://github.com/swapmyvote/swapmyvote/issues/298

**Comment by tdg** [comment]
Is #281 fixable?
If so, can we do that first then do this #298?

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [December 7, 2019 10:55 PM](https://github.com/swapmyvote/swapmyvote/issues/298#issuecomment-562877051 "2019-12-07T18:55:51Z - Replied by Github Reply Comments"):
> Is #281 fixable? 
> If so, can we do that first then do this #298?

There's no obvious fix.

Nor is there any obvious way to automatically detect which links are working.  I really think we need to gather more data on who it does and doesn't work for.

**Comment by tdg** [comment]
Ok, would it be a good use of time to go through customer support emails etc to find out a number of swaps partners affected?

**Comment by aspiers** [comment]
You mean *our* customers? Haven't we only heard from a very small handful
about this? Not a particularly useful sample size and tells us nothing
about how many *have* managed to find a working profile link. Better to
extract all links from the dB and test 20+ of them.

**Comment by aspiers** [comment]
@tdg Need comms to *all* Facebook users of app.  Please give your opinion on Andy's "swap garden" facebook group idea.  Upside: gives people a chance to find their swap partner.  Downside: people might use it to bypass the app with a horribly inefficient manual swap searching.

**Comment by tdg** [comment]
Spoke with Andy earlier about that idea. Whilst I think it's a creative idea, I'm not sure it will actually solve the problem. 

Is this possible?:
1) Work on #102 to get new users to consent to email address sharing 
2) Email all users (who've logged in with Facebook - and Twitter) to prompt them to log back in and then email their partners

**Comment by tdg** [comment]
3. Now that everyone who logs in consents to email sharing with partners, we can introduce them, and ask them to introduce each other in another medium too (eg social, or phone)

**Comment by baob** [comment]
I'm 75% of the way there on #102 ... I fully defined what I'm working on in #324

**Comment by aspiers** [comment]
@tdg In parallel with writing a new mail template to send to all our Facebook users, I think we need other comms on this via MC and Twitter.

**Comment by baob** [comment]
Decisions needed before doing a mailout: https://github.com/swapmyvote/swapmyvote/issues/336

**Comment by baob** [comment]
Also needed before doing coding for a mailout:  #337 and #324 need to be complete, or at least we need to confirm the endpoints used in the mail.

**Comment by aspiers** [comment]
Got the dataclip ready, about to create MC campaign.

**Comment by aspiers** [comment]
Done
