### ISSUE TITLE
Include all constituency parties in preferred voting options

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#3]
When asking who the voter would like to vote for (their _preferred_ choice), now include all of the parties from constituency parties lookup #2, but probably with the main (largest) parties at the top.

**UPDATE**: This issue may not make sense - please see comments.

**Comment by aspiers** [comment]
@tdg How is this different from #2?

**Comment by tdg** [comment]
This one is in the demand side of the user preferences, whereas #2 is in the supply side

**Comment by aspiers** [comment]
@tdg Are you sure?  If this is about who the voter would *like* to vote for (rather than who they're *willing* to vote for on behalf of someone else) then it could be a party for which there is noone standing in their own constituency.  Therefore I don't see how "now include all of the parties from constituency parties lookup #2" makes sense.  If we are aiming to be non-partisan then surely we should include all parties across the whole country, not just ones for which candidates are standing in the user's constituency.

**Comment by tdg** [comment]
Agreed. Apologies, I'm getting confused between _PREFERRED_ (all UK, ref #3) and _WILLING_ (voter's constituency, ref #2)

**Comment by tdg** [comment]
Resources: https://candidates.democracyclub.org.uk/api/docs/csv/

**Comment by aspiers** [comment]
OK thanks, so can you edit the original description accordingly?

**Comment by aspiers** [comment]
I've re-reviewed this and I don't understand why any changes are needed here.  We already offer all parties in the database as choices for what the user would prefer to vote for.  For example you could have a Scot living in England who might prefer to vote for the SNP - even though they cannot do that in their local constituency, it should be allowed as a valid preference.  So I'm tempted to think this issue can be closed, and would appreciate input from others on this.

In contrast, #2 very definitely requires work to implement (a fairly significant amount, actually).

**Comment by aspiers** [comment]
@tdg Please can you re-review my last comment and assess whether this can be closed?

**Comment by tdg** [comment]
> @tdg Please can you re-review my last comment and assess whether this can be closed?

It makes sense to close it. The only vestige that might be helpful is the question of reflecting more parties in the ‘preferred’ options. In fact I think the original issue may have conflated including all parties as ‘preferred’ options with something about constituencies which has for a long time not made sense!
