### ISSUE TITLE
Show prospective partners' constituency's leave/remain vote as well as parties bar charts

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#30]
Source: https://docs.google.com/spreadsheets/d/1wTK5dV2_YjCMsUYlwg0l48uWWf44sKgG8uFVMv5OWlA/edit#gid=893960794
Chris Hanretty's estimates

**Comment by aspiers** [comment]
Sadly Brexit is done now so this no longer applies.
