### ISSUE TITLE
Email people who've set prefs, but gone no further

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#302]
- [x] Create dataclip with their email addresses, names, timestamps
- [x] Import to mailchimp
- [x] Write copy and CTA
- [x] Send email out

OR

- [ ] Create dataclip with their email addresses, names, timestamps
- [ ] Write copy and CTA
- [ ] *Use mailgun somehow to send the emails?*

**Comment by tdg** [comment]
> - [ ] *Use mailgun somehow to send the emails?* 

@aspiers how would we do this?

**Comment by tdg** [comment]
Alternative way of doing this - could we automate it?
cc @baob

**Comment by aspiers** [comment]
We already have a rake task for sending vote reminder emails:

https://github.com/swapmyvote/swapmyvote/blob/master/lib/tasks/users.rake

This can be manually triggered via Heroku CLI.

We could take the same approach for any other emails we want to send,
but it does require a small amount of coding.

**Comment by tdg** [comment]
> We already have a rake task for sending vote reminder emails:
> 
> https://github.com/swapmyvote/swapmyvote/blob/master/lib/tasks/users.rake
> 
> This can be manually triggered via Heroku CLI.
> 
> We could take the same approach for any other emails we want to send,
> but it does require a small amount of coding.

Brilliant - who can take this on?

**Comment by aspiers** [comment]
Sent via mailchimp but only reached 8k out of 11.2k users from data clip - mailchimp issue...

**Comment by aspiers** [comment]
@tdg Sounded like you understood what went wrong here - please can you address?

**Comment by tdg** [comment]
Will do, if we stay open tomorrow!

**Comment by tdg** [comment]
Emailed everyone
