### ISSUE TITLE
On polling day Thursday 12th at 06:59 - Close for swaps

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#304]
We need to update the home page with appropriate copy (this exists I think already, pretty much)

**Comment by tdg** [comment]
@aspiers can I assign you to this please?

**Comment by aspiers** [comment]
Sure but please remind me nearer the time!

**Comment by tdg** [comment]
Can we capture using calendar reminders?

**Comment by aspiers** [comment]
Yes good idea, create a new shared google calendar?

**Comment by aspiers** [comment]
Done
