### ISSUE TITLE
Login modal can't be scrolled on mobile devices

### ISSUE THREAD

**Issue by stevebaxter** [swapmyvote/swapmyvote#316]
On some mobile devices the "login" modal will be poorly positioned and isn't scrollable. In particular, the information on privacy and consent may be clipped and inaccessible. We should make sure this can be scrolled into view.

This was reported by one used on the WhatsApp group.

**Comment by aspiers** [comment]
This was previously tracked in #257 for which there was a different type of fix, but I suspect scrapping `position: fixed` is the main fix.

**Comment by aspiers** [comment]
But also, there shouldn't be a big margin above the modal on mobiles.

**Comment by aspiers** [comment]
Closed by #329.  @stevebaxter FWIW GitHub doesn't properly understand the syntax "fixes: #320, #316" and only auto-closed #320 ;-)
