### ISSUE TITLE
voter exchange of emails at swap confirm time

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#324]
Possible solution to #281 @aspiers @tdg 

The essentials:

- swap proposer gives consent (or not) to share their email address at time of proposing the swap
- swap recipient gives consent (or not) to share their email address at time of confirming the swap
- when swap is confirmed, any emails consented to will be sent from SMV standard address containing email address, twitter profile and fb link with a big caveat.

Since we're only using one authentication method (twitter, email, FB) there should be no ambiguity about which email address we're using, only need a checkbox on the form.

The swap form (propose or confirm) will need to explain the need for this consent for anyone authenticating with FB.

**Comment by aspiers** [comment]
Sounds great to me, thanks!  Looks like you're working on this which is awesome - as part of that please can you make sure that your solution deals with this logic bug:

https://github.com/swapmyvote/swapmyvote/blob/88415c9e3cc73141638081d2453e8d60cec89a37/app/models/user.rb#L285

If for some reason a fb user declined to share their profile URL, this would share their email address instead.

**Comment by tdg** [comment]
Could I suggest that consent be mandatory for the user to progress, as it is with login at the moment (in case that isn't the plan above!).

**Comment by baob** [comment]
If you have two twitter users then there’s no need for them to swap emails in addition to twitter profiles.
