### ISSUE TITLE
[Airbrake] [Production] Could not find a valid mapping for path "/auth/facebook/callback"

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#328]
**Airbrake error:** [#6431](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/2630647628976856431)
**Airbrake project:** swapmyvote

**Error type:** `RuntimeError`
**Error message:** `` Could not find a valid mapping for path "/auth/facebook/callback" ``
**Where:** `<no information>`
**Occurred at:** Dec 09, 2019 14:27:12 UTC
**First seen at:** Dec 09, 2019 14:27:12 UTC
**Occurrences:** 0 (0 since last deploy on Dec 08, 2019 21:20:32 UTC)
**Severity:** `error`

**URL:** [https://www.swapmyvote.uk/auth/facebook/callback?code=AQAi-RF2zwL6iG63NKFryqIWAqHxTgDbeB4s2uWRn9sXxHTkCNxtmtF3PJ8tuZa4yskDypUjoDkAYtsKhMXBsATCSdxwhthLrmedPMv2ngziqKiCQF-vkDew2r2HTDZpbQo7jWMxRRbhYv5_5y8mwU85lyWNJZhgjOduMN1SevK4ID7_9_eRU2vNWFPP_QofpShp1LlQpH-U8n8QLsmrsAMPhuqFuLnS91lwBUCEVcOQOKorY_R-HA1BbO0_ArX-ekzf-jtbRjQyywLieCynfo3hp3FZzOdFP_3JRkMPyx3HVbhZn6FOT2BRjuc8BSscb2s&state=214dd86304adf468a8bae44eb989ca9bdb407d4f0e143517](https://www.swapmyvote.uk/auth/facebook/callback?code=AQAi-RF2zwL6iG63NKFryqIWAqHxTgDbeB4s2uWRn9sXxHTkCNxtmtF3PJ8tuZa4yskDypUjoDkAYtsKhMXBsATCSdxwhthLrmedPMv2ngziqKiCQF-vkDew2r2HTDZpbQo7jWMxRRbhYv5_5y8mwU85lyWNJZhgjOduMN1SevK4ID7_9_eRU2vNWFPP_QofpShp1LlQpH-U8n8QLsmrsAMPhuqFuLnS91lwBUCEVcOQOKorY_R-HA1BbO0_ArX-ekzf-jtbRjQyywLieCynfo3hp3FZzOdFP_3JRkMPyx3HVbhZn6FOT2BRjuc8BSscb2s&state=214dd86304adf468a8bae44eb989ca9bdb407d4f0e143517)
**File:** `/GEM_ROOT/gems/devise-4.7.1/lib/devise/mapping.rb`

**Backtrace:**
```
/GEM_ROOT/gems/devise-4.7.1/lib/devise/mapping.rb:51:in find_by_path!
/GEM_ROOT/gems/devise-4.7.1/lib/devise/omniauth.rb:19:in block in <main>
/GEM_ROOT/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:491:in fail!
/GEM_ROOT/gems/omniauth-oauth2-1.6.0/lib/omniauth/strategies/oauth2.rb:78:in rescue in callback_phase
...
Caused by OAuth2::Error: {"message"=>"This authorization code has been used.", "type"=>"OAuthException", "code"=>100, "fbtrace_id"=>"ANHDJFWrDfwE9QWHNbtql5p"}: 
{"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"ANHDJFWrDfwE9QWHNbtql5p"}}
```

**Comment by stevebaxter** [comment]
Hmm, FB sign-in is working for me. Any ideas how to reproduce?

**Comment by aspiers** [comment]
Might well have been an issue with being logged in via the old omniauth system during upgrade to devise.

**Comment by aspiers** [comment]
Seeing a whole flood of occurrences of this starting this morning - 113 so far.

**Comment by aspiers** [comment]
Up to 133 already - this is **BAD**.

**Comment by aspiers** [comment]
Happening for both Facebook and Twitter callbacks.  @stevebaxter reproduced by cancelling oauth request on facebook's end.  Discussing in #email channel on Slack.  Could be due to not handling oauth failure properly any more.  Used to be done like this:

https://github.com/swapmyvote/swapmyvote/commit/5d4ff93e84b4682947d48017388e417639b47b5e

but with Devise this is the way:

https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-when-the-user-can-not-be-authenticated
