### ISSUE TITLE
Decide license for code

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#33]
Currently the README says the license is TBD.  This really should be sorted before we go live for GE2019.

## Goals

- **Transparency and trustability**: Allow anyone to audit the code 
- Allow people to contribute easily
- Limit abuse / misuse of the code-base

**Comment by aspiers** [comment]
I don't own the copyright so this can only be decided by you guys.  However I'm happy to provide advice if needed.

**Comment by aspiers** [comment]
I would maybe suggest the AGPL: http://www.gnu.org/licenses/license-list.html#AGPLv3.0

**Comment by jpallen** [comment]
I am happy to license my contributions under the AGPL 👍

**Comment by aspiers** [comment]
Discussed with @tdg, will update issue description accordingly.

**Comment by aspiers** [comment]
It's becoming a major issue not having a license, because we don't have any copyright assignment process in place.

**Comment by aspiers** [comment]
@tdg @jpallen and I discussed this a while back, and based on the above goals we decided that for now we will keep all rights reserved and ask all contributors to assign copyright to Forward Democracy.  I have since set up the cla-bot to semi-automate this process.
