### ISSUE TITLE
Email sign in pre-fills with name

### ISSUE THREAD

**Issue by egglestn** [swapmyvote/swapmyvote#330]
Create a new account with email, sign out, then go to the "sign in again" page. The email field has been pre-filled with user name, but it should be user email

**Comment by aspiers** [comment]
Urgh, this is not good.

**Comment by aspiers** [comment]
Thanks for finding and reporting!

**Comment by fkorning** [comment]
@egglestn I can't repro this. might it be a brower-fill issue?

**Comment by egglestn** [comment]
Agreed, I can't reproduce it now either. Happy to close

**Comment by fkorning** [comment]
not a bug. can't repro.
