### ISSUE TITLE
Share by email prompt mailto 

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#335]
When we offer people to share with FB or Twitter, we should ask them to share by email - so we can get into the 'email social graph'

**Comment by aspiers** [comment]
@tdg What's this about?

**Comment by tdg** [comment]
When we offer people to share with FB or Twitter, we should ask them to share by email - so we can get into the 'email social graph'

**Comment by aspiers** [comment]
Downgraded to M3.5 - sorry but I'm guessing unlikely we'll get to this this time and we may have to live without it.
