### ISSUE TITLE
facebook profile link - backlogged swaps decisions

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#336]
@tdg @aspiers We have decisions to make about the backlog of users who have confirmed or unconfirmed swaps and may be hit by the facebook profile sharing issue (See https://github.com/swapmyvote/swapmyvote/issues/298). We need to decide

- [ ] which cases do we need to target by mailout
- [ ] what wording do we use in the various cases

We need to consider

* can they trust the other user by seeing their social profile somewhere
* can they establish direct contact.

There are (at least) six cases to consider, depending on how both ends of the swap authenticated to our app. 

* Twitter/Twitter - probably no need for mailout - they can establish contact
* Twitter/Facebook - probably facebook user should be encouraged to share email OR join twitter
* Twitter/Email - probably Email user should be encouraged to share email OR join twitter
* Facebook/Facebook - both users should be encouraged to share email
* Facebook/Email - probably both users should be encouraged to share email
* Email/Email - probably both users should be encouraged to share email

**Comment by tdg** [comment]
Great thinking and I think I would be a bit more liberal, so:

>can they trust the other user by seeing their social profile somewhere

Is no longer a central guiding principle, but we should include it where it exists
 
>can they establish direct contact.

Becomes essential

Therefore, in turn, my takes:
There are (at least) six cases to consider, depending on how both ends of the swap authenticated to our app.

> Twitter/Twitter - probably no need for mailout - they can establish contact 
AGREED

> Twitter/Facebook - probably facebook user should be encouraged to share email OR join twitter
Both should share social and email

> Twitter/Email - probably Email user should be encouraged to share email OR join twitter
Both should share email and Twitter should share social

> Facebook/Facebook - both users should be encouraged to share email
AGREED (plus facebook still)

> Facebook/Email - probably both users should be encouraged to share email
AGREED (plus facebook facebook still)

> Email/Email - probably both users should be encouraged to share email
AGREED

**Comment by baob** [comment]
@tdg It looks like we may be able to come up with one wording then, asking (in all cases but twitter/twitter) the swapper to give consent to share their email address (by linking them to the endpoint we define via https://github.com/swapmyvote/swapmyvote/issues/337 )

**Comment by tdg** [comment]
Dear NAME,

Thank you for joining Swap My Vote! Together we are making votes count, two at a time. 

Vote swapping relies on trust between swap partner, and what the platform does to help is to introduce you to each other. 

Unfortunately, due to the way that Facebook settings now work, this link has broken for many people who logged in with Facebook, and your partner may not be able to be in touch with you. 

Therefore you need to take action to create contact between you. Please _click here now_ to let your partner know your email address. They will also be prompted to do the same for you, and that way you will be able to contact each other. 

_Take action now_

Thank you,
Forward Democracy!

Swap My Vote Team
FOOTER as usual

**Comment by tdg** [comment]
Draft ☝️

**Comment by tdg** [comment]
We should also email their partners of whichever login flavour (I guess only Twitter is necessary) with a similarly worded one

**Comment by baob** [comment]
> We should also email their partners of whichever login flavour (I guess only Twitter is necessary) with a similarly worded one

To me, it seems that draft email will do, for both ends of the swap, unless we have a twitter/twitter connection ?  Actually, it will _nearly_ do ... it's not appropriate for en email/email connection (FB profiles don't come into play there) 

If I've got that wrong we'll need to pick out some of the cases individually, or grouped.

**Comment by tdg** [comment]
Okay, enough to go on for now?

**Comment by baob** [comment]
That's great, thank you.

**Comment by aspiers** [comment]
Guys let's not over-complicate this with 6 different cases - it's unnecessary and will take too long.  We can just mail **everyone** about the Facebook problem, and I see no good reason to avoid encouraging **all** users to give consent to share their email, even if they are in a Twitter/Twitter swap.

This shrinks 6 cases down to one.  Furthermore I already fixed the text on the confirmed swap page:

![image](https://user-images.githubusercontent.com/100738/70579190-4a785d00-1bc9-11ea-86ea-7f4d116fc51f.png)

in this commit:
https://github.com/swapmyvote/swapmyvote/commit/68a54f1db35f16b60a9603bfe8d4e73d8a9cfbcb

although we still need to reuse that in the swap confirmation email (filed as #346).

**Comment by aspiers** [comment]
Now handled by #298.
