### ISSUE TITLE
Confused login with social email clash report

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#342]
![Screen Shot 2019-12-10 at 20 42 37](https://user-images.githubusercontent.com/95868/70567332-aae9a900-1b8d-11ea-8c02-5d16b9596459.png)

**Comment by tdg** [comment]
![Screenshot_20191210-203447](https://user-images.githubusercontent.com/95868/70570059-17b37200-1b93-11ea-82f0-750afa34fbbf.jpg)

**Comment by tdg** [comment]
"

I guess they must. I tend to let Google log me in to everything so I'm not sure. Facebook for sure is that email. I'll check Twitter brb
--
  | Yep. Same

"

**Comment by aspiers** [comment]
Huh?  They're trying to log in by email?  What does the above comment mean?

**Comment by tdg** [comment]
The user had logged in with all three login options at different times, and of course the email associated (with social accounts as well) had already been taken.

**Comment by aspiers** [comment]
Had logged in successfully or tried to log in and failed? Still confused,
are you saying user is just doing it wrong or there is an actual issue
here?

**Comment by aspiers** [comment]
Too late to get to the bottom of this.
