### ISSUE TITLE
'Desirable' vote swap fails to find partner 5 times

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#343]
Just on FB msgs with https://www.facebook.com/bryony.davis.16 who logged in with FB. 

I wonder if her situation is trying to tell us something - she’s a desirable swap, but has had 5 fall through… 
`
```
I've had no response from three and turned down by the fourth.  Waiting on 5th.  Am in Monmouthshire - Conservative seat but where Labour just might get in.  Am willing to vote labour and wanting a Green swap as am a Green party member.```

**Comment by tdg** [comment]
She wonders if it's her profile picture putting people off… my hunch is there's something else at play

**Comment by tdg** [comment]
Email is bryony@tiscali.co.uk

**Comment by aspiers** [comment]
She finally got a confirmation - just bad luck?
