### ISSUE TITLE
Allow developers to skip SMS verification

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#360]
Be great to be able to test with multiple accounts without feeling guilty

**Comment by tdg** [comment]
Be great to be able to test with multiple accounts without feeling guilty

**Comment by aspiers** [comment]
Yes actually the guilt of wasting money on extra SMS is minute compared to the importance of allowing testing from multiple email accounts belonging to the same person who only has one phone.

So we should create a new admin view and route to controller action which allows admins to manually verify a fake phone number as if the SMS process had been done.
