### ISSUE TITLE
Separate out any special 'election day only' copy changes

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#369]
@tdg @aspiers 

https://forwarddemocracy.slack.com/archives/C68EF6FUZ/p1576153652158200?thread_ts=1576152715.155000&cid=C68EF6FUZ

**Comment by aspiers** [comment]
@baob @tdg Can you remember what this was about?  Haven't we already done this with the "new" `SWAPMYVOTE_MODE` environment variable?

**Comment by baob** [comment]
@aspiers Right now, I don't remember what motivated this. And it does seem to overlap with changes you were making at the same time. 

Delete it. If it was something important, it will surely become apparent, anyway.

**Comment by aspiers** [comment]
I re-read the linked Slack discussion and I'm pretty sure the environment variable solves this.

**Comment by aspiers** [comment]
For example:

- https://github.com/swapmyvote/swapmyvote/blob/master/app/views/home/index.html.haml
- https://github.com/swapmyvote/swapmyvote/tree/master/app/views/home
