### ISSUE TITLE
https for naked domain(s)

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#37]
https://www.swapmyvote.uk/
http://www.swapmyvote.uk/
http://swapmyvote.uk/ ALL WORK

https://swapmyvote.uk/ Doesn't work

**Comment by tdg** [comment]
"It's a bit tricky, because heroku manages the SSL cert, but the root domain (without www) points to the DNS provider for a simple redirect, but they don't have the SSL cert to support Https on it

If we want that to work, we need to point it at heroku, but only certain DNS providers support the alias method needed for root domains (this is why www is easier to work)"

There might be registrars that are better at supporting this than our current.

**Comment by aspiers** [comment]
@tdg Who wrote that text in quotes?

Furthermore, Twitter login works with http://swapmyvotedev.herokuapp.com but not with https://swapmyvotedev.herokuapp.com.

I don't think I can resolve this one without help from @jpallen or whoever holds the keys to the DNS records (which are managed by 123-reg by the looks of it).

**Comment by tdg** [comment]
>@tdg Who wrote that text in quotes? 
@jpallen did

>I don't think I can resolve this one without help from @jpallen or whoever holds the keys to the DNS records (which are managed by 123-reg by the looks of it).

I can help with that - let's take this one to Slack

**Comment by jpallen** [comment]
> Furthermore, Twitter login works with http://swapmyvotedev.herokuapp.com but not with https://swapmyvotedev.herokuapp.com.

I suspect this how the callback URL is configured. I would suggest creating a new Twitter app under `@swapmyvote`, and pointing staging at that. Then you can adjust it and change it as needed. Currently it's an app on my personal account.

**Comment by aspiers** [comment]
Yes that's a good suggestion.

One key question I have for you both is: why don't we use Heroku to manage DNS?  Wouldn't that simplify everything?

**Comment by tdg** [comment]
> One key question I have for you both is: why don't we use Heroku to manage DNS? Wouldn't that simplify everything?

I don't know why not! @jpallen do you remember why not?

**Comment by tdg** [comment]
I've applied for a Twitter Developer account

**Comment by aspiers** [comment]
[**@tdg**](https://github.com/tdg) commented on [November 10, 2019 12:01 AM](https://github.com/swapmyvote/swapmyvote/issues/37#issuecomment-552148675 "2019-11-10T00:01:12Z - Replied by Github Reply Comments"):
> > One key question I have for you both is: why don't we use Heroku to manage DNS? Wouldn't that simplify everything?
> 
> I don't know why not! @jpallen do you remember why not?

Because it turns out Heroku doesn't support that.

**Comment by tdg** [comment]
We could use a service like https://www.nakedssl.com/heroku for this

**Comment by aspiers** [comment]
Tom used nakedssl to set this up, and I've checked it and the 301 redirection is working perfectly :+1:

**Comment by tdg** [comment]
Since that, I've also found this, in case we need it later at any point 
https://github.com/pixielabs/letsencrypt-rails-heroku
