### ISSUE TITLE
Allow login based on email

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#38]
This would open up the site to people who can't or won't use Twitter or Facebook.  Dependent on #7 otherwise it would be too easy for spammers to attack the site with lots of fake profiles.

**Comment by egglestn** [comment]
Will need to update the privacy policy when this is implemented, I'm currently only adding FB and twitter under https://github.com/swapmyvote/swapmyvote/issues/73

**Comment by aspiers** [comment]
Very good point!  Yes, let's do that in the same PR as the implementation.

**Comment by aspiers** [comment]
https://github.com/omniauth/omniauth-identity is probably a good option for this.

**Comment by aspiers** [comment]
This is now critically urgent because Facebook have not responded to our app appeal within a day like they said they would.  Based on other text they've written it could be as much as 2 weeks.  I've submitted a separate app review which includes asking for the new `user_link` permission, so hopefully this will hurry them along but there's zero guarantee.

**Comment by tdg** [comment]
New paragraph needed (under Facebook and Twitter paragraphs)

Email login
When you sign up to swapmyvote with your email address, you voluntarily share your email address with your proposed and confirmed vote swap partners

**Comment by tdg** [comment]
Rogue `//` at start of email address in two places:

> You can reach out to USERNAME by email at EMAIL ADDRESS to get to know your swap partner.

in web view and 

>We'll send some reminders to USERNAME to remind them to vote for your chosen party on December 12th, and we'll ask them for confirmation once they have. In the meantime, why not reach out to EMAIL LINK directly?

**Comment by aspiers** [comment]
Done both of these
