### ISSUE TITLE
Update existing swap preferences from home page form on login

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#42]
If a user set swap preferences on a previous log-in, and then populates the form on the initial landing page before logging in, it will ignore the values on that form and revert to the values previously set for that user.  This is counter-intuitive and should be fixed.

**Comment by aspiers** [comment]
This might have actually been broken by 90440b2bd6 just like #36 (probably) was.

**Comment by aspiers** [comment]
Pretty sure I know what the issue is here, and am working on this.

**Comment by tdg** [comment]
Can we move this to Done?
