### ISSUE TITLE
404s on swapmyvotedev.herokuapp.com

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#449]
https://swapmyvotedev.herokuapp.com/ returns 404:

![image](https://user-images.githubusercontent.com/100738/121805874-07c39500-cc45-11eb-8615-04dc1ba2c038.png)

This happened some time in between GE2019 and BE2021.

Slack convo: https://forwarddemocracy.slack.com/archives/C68EF6FUZ/p1622127903006800

**Comment by aspiers** [comment]
I have tried *many* things to fix this and am totally at a loss.

**Comment by baob** [comment]
Given that requests from the browser never even reach our backend, is this this something we can solve at all ?  Maybe it needs heroku support ?
