### ISSUE TITLE
rake db:migrate installation issue

### ISSUE THREAD

**Issue by timjoyce11** [swapmyvote/swapmyvote#46]
tim@ASUS MINGW64 /c/swapmyvote (master)
$ rake db:migrate

C:/Ruby26-x64/lib/ruby/2.6.0/fileutils/version.rb:4: warning: already initialized constant FileUtils::VERSION
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils/version.rb:4: warning: previous definition of VERSION was here
C:/Ruby26-x64/lib/ruby/2.6.0/fileutils.rb:1267: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils.rb:1285: warning: previous definition of S_IF_DOOR was here
C:/Ruby26-x64/lib/ruby/2.6.0/fileutils.rb:1538: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils.rb:1566: warning: previous definition of DIRECTORY_TERM was here
C:/Ruby26-x64/lib/ruby/2.6.0/fileutils.rb:1595: warning: already initialized constant FileUtils::OPT_TABLE
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
C:/Ruby26-x64/lib/ruby/2.6.0/fileutils.rb:1649: warning: already initialized constant FileUtils::LOW_METHODS
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
C:/Ruby26-x64/lib/ruby/2.6.0/fileutils.rb:1656: warning: already initialized constant FileUtils::METHODS
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.3.0/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
C:/swapmyvote/db/migrate/20141223112651_create_users.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
C:/swapmyvote/db/migrate/20141223112651_create_users.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by baob** [comment]
> Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

I've seen that before (this repo) and got around it, somehow. Will try and figure it out. It definitely didn't need a code fix.

Are you on the right ruby (see Gemfile) and with all gems up to date ?

Have you tried `bundle exec rake db:migrate` ?

**Comment by timjoyce11** [comment]
tim@ASUS MINGW64 /c/swapmyvote (master)
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

tim@ASUS MINGW64 /c/swapmyvote (master)
$ gem update
Updating installed gems
Nothing to update

tim@ASUS MINGW64 /c/swapmyvote (master)
$ bundle exec rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
C:/swapmyvote/db/migrate/20141223112651_create_users.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
C:/swapmyvote/db/migrate/20141223112651_create_users.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by baob** [comment]
Have you done `rake db:create` ? .... I'm wondering if that was the step I missed that caused the same problem.

**Comment by aspiers** [comment]
Yeah I've just tested and confirmed this is a non-issue - you need to do `bundle exec rake db:setup` instead which takes care of everything.

I'll fix the README now.

**Comment by aspiers** [comment]
Ah slight correction, I think `db:setup` does `db:schema:load` so the issue with migrations is genuine.  Will try to fix that too.

**Comment by ursaleotim** [comment]
awesome.  that worked.
