### ISSUE TITLE
Willing party should probably allow multiples

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#476]
Scenario: theres a movement towards a progressive alliance of libdem, labour, green (with or without co-operation of party hierarchy).  In that case, 3 obvious kinds of voters crop up

* lab, willing to vote libdem or green
* green, willing to vote lab or libdem
* libdem, willing to vote lab or green.

Would be nice to accommodate that. Probably not a trivial task.  

@tdg @aspiers

**Comment by aspiers** [comment]
I'm 99% sure this is a duplicate of an existing (probably old) issue - have a search through :-)

**Comment by baob** [comment]
Ah ... appears to be a duplicate of #27
