### ISSUE TITLE
Unify email footers

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#479]
For some bizarre reason each email template has its own footer instead of using a common layout.  This leads to horrible code duplication which needs to be fixed.

**Comment by baob** [comment]
There's an in-progress branch for this at https://github.com/swapmyvote/swapmyvote/compare/master...baob:swapmyvote:email-templates-refactor?expand=1

**Comment by aspiers** [comment]
Closed by #659.
