### ISSUE TITLE
Link to facebook profile is broken

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#48]
The link to a swap partner's facebook profile doesn't work, because it's constructed simply by appending the user id to https://facebook.com:

https://github.com/swapmyvote/swapmyvote/blob/7920e1fe9934fdcb7dcdb9bfa7a3c49ee83a065e/app/models/user.rb#L33-L35

Instead we should get the URL directly from omniauth:

https://stackoverflow.com/questions/30556175/rails-omniauth-get-a-real-facebook-profile-link

**Comment by aspiers** [comment]
I tried to figure out from https://findmyfbid.com/ how to construct a uid-based URL but failed ...

**Comment by aspiers** [comment]
So we can either use `auth.info.urls.Facebook` or `"https://facebook.com/#{auth.info.nickname}"` but either way we'll need a migration to add an extra field to the user table in the db, since there's nowhere to store this currently.

**Comment by egglestn** [comment]
If we were thinking of splitting out the fb / twitter stuffs into their own tables, is this a good opportunity to make the table structure changes?

**Comment by aspiers** [comment]
@egglestn Yes very good point - it could be, since then the new table would include a `profile_url` field.

**Comment by aspiers** [comment]
For @alanjc7 or anyone else who is following this sub-discussion but missing the context, we're referring to #44.

**Comment by alanjc7** [comment]
Thanks, having read both I think it would be sensible to add a table for users social profiles as part of this issue. Something like `users_social_profiles`, with just `user_id`, `facebook_url` and `twitter_url` as columns initially

**Comment by aspiers** [comment]
Not quite, the columns would be `user_id`, `provider` (with values like `facebook` or `twitter` - this could even be an `enum`), and `profile_url`.

**Comment by alanjc7** [comment]
Ah yeah, that makes more sense - much easier to allow other social platforms in the future.

**Comment by aspiers** [comment]
Exactly 😁

**Comment by egglestn** [comment]
Would be nice to move over the (other) profile-related columns from the users table: (provider), name, email, image, token, expires at? Or would that upset omniauth?

**Comment by aspiers** [comment]
We need a single name and email regardless of how many social networks are tied to the user, so we need to keep those fields. But we could have provider-specific fields in the `Identity` table too, for storing details from the omniauth response. Omniauth doesn't make any assumptions about model structure.

**Comment by egglestn** [comment]
Still struggling to get the profile link from omniauth. 

The stackoverflow post above is from 2015, and sadly, I think privacy has overtaken fb since then.

Here are two newer updates: https://stackoverflow.com/questions/29152500/get-real-profile-url-from-facebook-graph-api-user and https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/

**Comment by egglestn** [comment]
https://developers.facebook.com/docs/graph-api/reference/user suggests we aren't going to get there - I'm debugging directly against the url and even some of the documented fields don't seem to provide results.

We could possibly hack something together using a search query and the person's full name, but it feels messy. Or we could ask fb signin users to provide their page link directly? But there's a lot of scope for user error there

**Comment by aspiers** [comment]
What about https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_link ?

**Comment by aspiers** [comment]
OK so based on that text I'm not sure whether the `user_link` permission will give us links for profiles of people who aren't in the friend list of the logged in account, but it's worth a try.  Looks like we need to include that permission in [the `scope` parameter when setting up the omniauth middleware](https://mkdynamic.github.io/omniauth-facebook/#usage).

**Comment by aspiers** [comment]
I could have sworn that the list of permissions used to be configurable via https://developers.facebook.com/apps but I can't find it any more so I guess they now require the app code to set the scope programmatically.

**Comment by egglestn** [comment]
Looks like /user_link is configurable in facebook app management, but it needs to be by an app admin (developer permissions don't cut it), so please would you have a go?

**Comment by aspiers** [comment]
See previous comment - I just spent 20 minutes looking for it but can't find the bloody thing anywhere!

**Comment by aspiers** [comment]
Having said that I think using `scope` as per above is a better approach anyway since then developers can propose changing the scope via PRs.

**Comment by aspiers** [comment]
See also https://developers.facebook.com/docs/facebook-login/permissions#reference-default for the list of default permissions.  Maybe in more naive times the profile URL used to be in there.

**Comment by aspiers** [comment]
#94 is hopefully a step in the right direction, but we can't merge it until we get the permission granted, and app review is currently blocking on #76, #90, and #93.

**Comment by aspiers** [comment]
My previous comment was wrong - we actually have to get this functionality working with the facebook test apps *first*, then we can make a screencast and submit it as part of the app review which requests the permission for the live facebook app.  So this is not blocked but rather very urgent.
