### ISSUE TITLE
Decide how to handle duplicate EC party registrations

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#491]
The Electoral Commission has two registers of parties, one for NI, and one for GB.  Some parties are apparently registered twice, by looking at the EC "Entity Name" (though they differ in registration code). These include:

 "Animal Welfare Party",
 "Common Good",
 "Conservative and Unionist Party",
 "Green Party",
 "Independent Network",
 "Libertarian Party",
 "National Front",
 "Real Democracy Party",
 "Restoration Party",
 "UK Independence Party (UKIP)",
 "UK Voice",
 "Veterans and People’s Party"
 
 Other parties are variously registered to either GB or NI
 
 Question: How do we deal with this ?
 
 We can't leave the list in this state or the dropdown will offer people 2 conservative parties.
 
 Possible solutions
 
 1. Assume the two parties are one and the same and only list one "Conservative and Unionist Party". This seems to me to be the most sensible
 
 2. List  "Conservative and Unionist Party (GB)" and "Conservative and Unionist Party (NI)" probably not an accurate reflection of reality.
 
 3. (Not really an option) Never show a list of every party, in which case the problem doesn't arise. But which means not allowing users to pick from a list of 'all parties' and not having an API (because there would be ambiguity over which party was meant by  "Conservative and Unionist Party",.
 
 TO ME IT LOOKS REALLY OBVIOUS (1) IS THE SOLUTION. But I wanted to check my thinking before going forward. 
 
 Relates to #458 
 
 /cc @tdg @aspiers

**Comment by baob** [comment]
It's worth noting that Democracy club do not appear to address this problem in their data, presumably because in their case no ambiguity arises because (effectively) they take option 3.

**Comment by tdg** [comment]
Would it be a bad idea to create a third entity, eg 'Conservative and Unionist Party' that contains both "Conservative and Unionist Party (GB)" and "Conservative and Unionist Party (NI)"? Is this what is meant by the DC pseudo model?

This approach could also be used to include other groupings such as 'Labour' and 'Labour and Coop' and 'Coop', and even (4.*) be used to group similar fringe parties that are recognisably of the same movement.

**Comment by baob** [comment]
Yes, I agree that's the way I'm thinking about it now, having talked to democracy club people about this.

The EC registrations model lets us deal with the two versions of the Conservative Party, by using the shared name, to treat them as one. 

I'm also thinking we need our own model, outside of the modelling done by the EC, which accounts for cases like  Labour and Co-op, which are distinct EC entities, but share a joint description. 

I've started documenting all this in [the code I'm developing](https://github.com/baob/swapmyvote/blob/259a12e1907cbe7ab7cddbb65292656e1caeb82a/db/fixtures/electoral_commission_parties.rb). I'm getting near to doing a pull request for just getting the EC data imported into a useful form.

**Comment by baob** [comment]
Note: Even using the above approach that may still leave ambiguities. For instance I've been told:

> The Labour Party in NI is disowned by Labour in Great Britain. And there are three Green Parties - England and Wales, Scotland and the northern branch of the Irish Green Party.

and

> the finances of a GB and NI party must be kept separate, even where it is just one actual party behind both registrations. But yeah, otherwise the degree of separation is down to the party. In the case of the Conservatives, it's a bit tricky because I can't find much information on the structure through the constitutions (I couldn't find one at all for their NI party). However, from their blog:
The new party will be autonomous on devolved issues, but remain a full part of the UK Conservative Party.

More on the DC slack [here](https://democracyclub.slack.com/archives/C02Q1MV53/p1624391758099000)

**Comment by aspiers** [comment]
Adjusted the title to make it clear what action this issue is requesting.

**Comment by baob** [comment]
This is how I intend to deal with the two major anomalies listed above. PR coming soon.

![image](https://user-images.githubusercontent.com/55932/124315145-68bafa80-db6b-11eb-974a-a3bebf57ce8d.png)

**Comment by aspiers** [comment]
Do you mean that you are introducing a new `registrations` model which has a 1:many association with the `party` model?

**Comment by baob** [comment]
At the moment all I've done is encapsulate the Electoral Commission data, and additionally dealt sensibly with the problems noted above (1) Double registration of conservatives, and (2) Labour and Co-op being two parties that behave as one. I'll do a PR for that and then separately deal with how that relates to our party model.
