### ISSUE TITLE
Better mobile support

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#5]
Better mobile support. At the moment the site is responsive, but very much feels like a web app, not a native app on mobile devices. Whether we can have one web app that works well on both, or need a more significant split of front-ends is an open question.

**Comment by aspiers** [comment]
#63 has provided a huge leap forwards on this issue.

**Comment by aspiers** [comment]
@tdg @georgecrawford Do you think we need to do anything else on this in the near future?  It looks good to me now so I'm tempted to close.

**Comment by tdg** [comment]
Looks good to me - happy to close

**Comment by georgecrawford** [comment]
Happy to close - let's raise separate issues for more specific things as we think of them
