### ISSUE TITLE
remove facebook option for login/signup?

### ISSUE THREAD

**Issue by joshr** [swapmyvote/swapmyvote#551]
iirc we can't support it anymore.

(and i spotted another issue about fixing Twitter, so i'm guessing we'll leave that in for now)

<img width="588" alt="Screenshot 2022-06-04 at 20 34 58" src="https://user-images.githubusercontent.com/36216/172024995-be704f37-3ed7-4c58-8748-2bdd13f8eb4c.png">
.

**Comment by baob** [comment]
This is already implemented on the live site.  I have just implemented it on the dev site.

For anyone who wants to replicate on their own site (@tdg @aspiers ) the trick is 
- edit the file `.env.development.local`
- add a new line with the text `export DISABLE_LOG_INS=all`
- restart your local server

Will close this ticket after everyone has had a chance to read. And feedback on the solution.

**Comment by baob** [comment]
I'm assuming we're all happy with this and closing.
