### ISSUE TITLE
make adjustments to allow for by-elections ending on the same day

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#556]
From Josh on Whatsapp:

> btw, previously the by-elections were on different dates, are we accounting for them being on the same date this time?

> i.e. are there any date-based triggers that change what you can do when the first one closed previously, and do we need to make changes to that

Adam on whatsapp:

> This may help refresh memories about the different modes and views https://github.com/swapmyvote/swapmyvote/blob/master/app/views/home/index.html.haml

**Comment by baob** [comment]
Okay, I'm not sure I see any problem here, it looks like we can cope with everything with these modes ?

![image](https://user-images.githubusercontent.com/55932/172057060-e7089b35-2bfc-4c51-bced-14c3a40a4b15.png)

**Comment by aspiers** [comment]
Only copy changes were needed but those are already done.
