### ISSUE TITLE
Offer non-voting users a way to sign up for the newsletter, on the live homepage and other views

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#557]
This could take the form of a form underneath the main 'swap my vote' app section with text to the effect of: 

> Not voting this time? 
> Sign up for future news from the Swap My Vote team and Forward Democracy
>[email field] [sign up button]

The newsletter is served by Action Network for which we can provide a form or API details.

**Comment by tdg** [comment]
For reference, #74 has useful internal links around consent

**Comment by baob** [comment]
@tdg  Let me know if this is what you wanted

![image](https://user-images.githubusercontent.com/55932/172233002-47ea48d9-41df-459f-ad6b-ea35cc0f036f.png)

**Comment by joshr** [comment]
this looks good, can it be centred?

I'm going to add some more css to reduce all that clutter in the form. i'll just do this inline in the partial.

**Comment by aspiers** [comment]
Merged #565, but actually @baob @tdg does this fully complete the issue? Since it only adds it to the `open_pre_elections` partial, and not other views.  I didn't check - are there are others where it is still missing?

**Comment by tdg** [comment]
You're right, @aspiers - the intention is to extend this function to the other states also

**Comment by aspiers** [comment]
Reopening until we check whether there are other states which are still missing the newsletter signup form.

**Comment by baob** [comment]
Apologies I completely forgot there was more to do ... originally I hesitated to apply it everywhere because I wasn't sure what was involved in making the form centered.

Just tell me which of the states need covering, and on which page, and I can get on with it.

**Comment by baob** [comment]
Moved the milestone to "stretch goals" because the case for "open" is already covered ... we can go to "open" without needing to do any more work here.

**Comment by baob** [comment]
Relates to https://github.com/swapmyvote/swapmyvote/issues/620
