### ISSUE TITLE
Update Mailchimp to Action Network

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#558]
There is currently (on the live, dormant homepage) email newsletter signup for Mailchimp.
This should be changed to Action Network who now provide the service. 
Privacy and other text should be reviewed and updated where needed.

**Comment by tdg** [comment]
https://github.com/swapmyvote/swapmyvote/blob/master/app/views/home/_closed_wind_down.html.haml

**Comment by aspiers** [comment]
See also https://github.com/swapmyvote/swapmyvote/blob/master/app/views/home/_mailchimp.html

**Comment by tdg** [comment]
Should also be on Closed_Warm-up
