### ISSUE TITLE
Mailchimp resource blocked in Firefox

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#56]
From a user email:

Hello,
I’m trying to sign-up to receive email notifications on your website but isn’t working in Firefox. Nothing happens when I click “Subscribe for updates”. I’m a web developer so I’ve instinctively reached for the inspector and when I do I can see this getting logged to the console:
The resource at “https://swapmyvote.us15.list-manage.com/subscribe/post-json?…86ca43a22f=&subscribe=Subscribe+for+updates&=1572957926500" was blocked because content blocking is enabled.
This is a privacy feature of Firefox, more info here: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection
I’d recommend getting this fixed asap as you’re probably missing out on quite a few potential subscribers!

**Comment by aspiers** [comment]
George has started looking at this with @tdg.

**Comment by tdg** [comment]
So it looks like what’s needed is the URL:
`https://swapmyvote.us15.list-manage.com/subscribe/post?u=7076c2b7a929106d12659c8ff&amp;id=990c72457a`
