### ISSUE TITLE
fix Rubocop errors

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#57]
Since #55 was merged we now have Rubocop infrastructure for linting style inconsistencies and other syntax issues.  This can be done via:

    bundle exec rubocop

Currently there are a number of different issues.  This can potentially be tackled via divide and conquer - my main suggestion would be to stick to PR per type of style issue (i.e. per category of Rubocop error or warning).  That will make the PRs easier to review, and should help minimise the need to block merging a PR, since it will avoid mixing more controversial changes with less controversial ones.

If anyone is planning to help with aspects of this, please coordinate on Slack to avoid stepping on other people's toes.  Thanks!

**Comment by baob** [comment]
I will pitch in by rubocopping any files I touch from now on.  I may add guard if that helps me with that goal.

**Comment by gabrielrumiranda** [comment]
Can I take this issue ?

**Comment by aspiers** [comment]
@gabrielrumiranda Your help is extremely welcome although please see my suggestion on the divide and conquer approach above.  I definitely **don't** want to have to review one giant PR which fixes every single rubocop issue at once, as that would be a huge amount of effort to get right.

**Comment by gabrielrumiranda** [comment]
Only left 4 errors, #59
