### ISSUE TITLE
make consent of sharing email address with partner mandatory

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#584]
- [x] copy changes (e.g. "I understand that my email address will be shared with my potential swap partner") to:
  - [x] `app/views/user/swaps/new.html.haml`
  - [x] `app/views/users/show/_confirm_incoming_swap.html.haml`
  - [x] `app/views/users/show/_confirm_outgoing_swap.html.haml` (should really be called `_waiting_for_swap_acceptance.html.haml` or similar)
- [x] update `User::SwapsController#create` to check that `params[:consent_share_email_chooser]` is `true`, and error if not.
- [ ] Browser-side validation for the checkbox.

**Comment by aspiers** [comment]
In additional to the copy change, this will require updating `User::SwapsController#create` to check that `params[:consent_share_email_chooser]` is `true`, and error if not.  It should also have browser-side validation for the checkbox.

**Comment by joshr** [comment]
proposed checkbox label copy: I understand that my email address will be shared with my potential swap partner

**Comment by joshr** [comment]
@baob lets do your shortest version:

I understand that my email address will be shared with Margaret S (test user)

and is it possible to make sure it goes to two lines on mobile? it looks like the other lines in your screenshot of that page are forced line breaks? sorry, i can't tell just from looking

**Comment by baob** [comment]
@aspiers  I didn't do client-side validation. Server side validation is working.

After reading https://www.jorgemanrubia.com/2019/02/16/form-validations-with-html5-and-modern-rails/ I concluded
- We should do client-side validation
- doing it properly is not trivial
- following the blog post authors recommend method for consistent client-side/server-side validation s a good approach
- we should do it when there is less pressure.

If you agree we can raise an issue for this

**Comment by baob** [comment]
closed by the combination of #596 being merged and #609 covering the remaining task.
