### ISSUE TITLE
redesign "Log in" modal flow

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#591]
One problem with the "Log in" modal (see screenshot below) is that it is used as a precursor for both for registrations and logins to already registered accounts, even though the text only talks about login rather than registration - so that's confusing to the user.

A second, consequent problem is that it is not a good place to ask for consent to process personal info, because we should only do that once per user at registration time (as per #245).

To elaborate: after clicking "Already been here? Log in", there is a checkbox asking for consent:

![image](https://user-images.githubusercontent.com/100738/172889381-8afa8247-308f-40aa-b131-a05c89a09401.png)

This kind of made sense when we had Facebook and Twitter logins enabled, because in that case a) login _was_ effectively registration, and b) there were no further screens on our side as part of the login process, so it made sense to gate login up front on obtaining consent.

But now we don't support Twitter/Facebook logins, only email.  And also we can't record consent in the db until we have an email address or some other form of identity, so it makes more sense to record consent at registration time, on the "Sign up with email" page.  Currently this page only asks for opt in to the newsletter, but it should really ask for consent to process personal info too.

**Comment by tdg** [comment]
NB Consent to process PI is mandatory (but must be understood)
Consent to newsletter must be non-mandatory

In many ways, having them at different parts of the flow can be a feature not a bug, as it means both are likely toi be considered accordingly to the user's intentions.

**Comment by aspiers** [comment]
Sure, to be clear I'm not arguing for removing the ability to opt in to the newsletter at other places.  But:

1. It makes no sense to ask for consent to process PII _every_ time they login.
2. If we can (again) offer sign-up to newsletter at registration, I think we should do it.

Also we can make it clear which is mandatory via the usual red asterisk superscript plus corresponding footnote.

**Comment by baob** [comment]
> 1. It makes no sense to ask for consent to process PII _every_ time they login.

💯

**Comment by baob** [comment]
Does the title "rethink" mean this still needs refinement ?  It doesn't look actionable to me, states a problem, with no direct suggestions for a solution ?

**Comment by aspiers** [comment]
The action is to figure out a solution and then file tasks for the implementation.

**Comment by aspiers** [comment]
@tdg Please can you revisit this and assess urgency for GE2024?

**Comment by tdg** [comment]
Yes it seems urgent, but I don't know what the solution would be @aspiers

**Comment by baob** [comment]
I think the proposed solution is in the first comment isn't it ?

> it makes more sense to record consent at registration time, on the "Sign up with email" page.

**Comment by tdg** [comment]
Thanks @baob that makes sense. 

In have a sense there is also something about returning users logging in, and not needing to re-consent (but I suppose maybe needing to be able to remove consent)?

**Comment by stevebaxter** [comment]
Now we only support email, I would suggest we:

1. Remove this login "choices" modal - it does nothing except get in the way
2. Go straight to the "Sign up with email" page
3. Add a mandatory "data processing" checkbox to that page

**Comment by baob** [comment]
@aspiers @stevebaxter where are we with this ? 

If we're going to have any chance of doing the wizard thing ( #922 ) this needs to be either merged or discarded ... otherwise too many parallel changes to the same piece of code.

**Comment by stevebaxter** [comment]
This is done in #897. Waiting for @aspiers to merge.
