### ISSUE TITLE
Postcodes to look up constituency

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#6]
Use post-code look up to let people find their constituency easily.

**Comment by tdg** [comment]
Superseded by discussion in #8

**Comment by aspiers** [comment]
This one is pretty important.

**Comment by baob** [comment]
If we want to link to use postcodes to select constituencies we have three choices.

1) Use the new ONS constituencies table combined with a new ONS-based postcode table (or redis lookup, given the size of the table) and abandon the linkage to polling data in based on the old constituencies table.

2) Additional, establish link between ONS and original constituency (and thus polling data) by continuing the name-matching effort begun in #8 (which is as yet not merged)

3) Alternatively to (2), Find a new source of polling data that is linked to ONS ids

**Comment by aspiers** [comment]
https://codepen.io/gaz/pen/pNdwZz looks promising
