### ISSUE TITLE
Update Analytics suite 

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#611]
Overview of why needed (introduction copied below)
https://support.google.com/analytics/answer/11583528

Todo list 
https://support.google.com/analytics/answer/10759417

> Universal Analytics will be going away
> Last updated: March 16, 2022. Visit this page in the coming months for the latest information.
> 
> [Google Analytics 4](https://support.google.com/analytics/answer/10089681) is our next-generation measurement solution, and it's replacing Universal Analytics. On July 1, 2023, standard Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you [prepare to use Google Analytics 4](https://support.google.com/analytics/answer/10759417) going forward.
> 
> Understand what's going to happen
> Until July 1, 2023, you can continue to use and collect new data in your Universal Analytics properties.
> After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time.
> In the coming months, we'll provide a future date for when existing Universal Analytics properties will no longer be available. After this future date, you'll no longer be able to see your Universal Analytics reports in the Analytics interface or access your Universal Analytics data via the API.

**Comment by egglestn** [comment]
@tdg please would you share the google analytics tag id so I can test with it?

**Comment by tdg** [comment]
@egglestn have shared with you in Zulip

**Comment by egglestn** [comment]
Thanks, I'm away tomorrow, will pick it up on Thursday

**Comment by aspiers** [comment]
I may try to get to it tomorrow because we want to launch ASAP.  But if not then help very welcome!
