### ISSUE TITLE
Optimise potential swaps algorithm by excluding voters constituency

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#628]
At the moment we intially get a list of potential swaps disregarding
constituency. Then later, we refine the list by discarding swaps in the
voters constituency.

This is sub-optimal for by elections because in the later phase we're
throwing away half the potential swaps.

Note: if we're not going to implement #625 first, we may still have to
use the existing method (picking up all constituencies) in the case
where the user has not yet chosen a constituency.

Benefits:

- Fewer database transactions
- marginally faster web responses when swaps are re-calculated
- much less messy logs (coder benefit)

Follows investigative work in #617

**Comment by aspiers** [comment]
This seems like an absolute no-brainer.  We should never have included the voter's constituency in the first place when searching for swaps, and I'm confused why we did.

**Comment by baob** [comment]
I guess whoever did it was only thinking of the context of a general election, where it might seems reasonable to obtain results over 650 constituencies, then later discard the 1 constituency we don't want.

However taking that approach over a 2-party by-election means the second step discards half the results found in the first step. Which makes it much more obviously in need of optimisation.

**Comment by aspiers** [comment]
Yeah, but even in the GE case I don't see why an extra `WHERE` clause wouldn't have been added to the initial query.

BTW it seems to me that `SwapTrier` should be refactored into a separate class, probably with a subclass for each strategy.  Probably `app/models/user.rb` isn't the best place for it, since it's about more than just one user.

**Comment by baob** [comment]
> `SwapTrier` should be refactored into a separate class

Agree
