### ISSUE TITLE
ask consent for cookies

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#65]
I assume we now need to explicitly ask for consent before storing cookies :-(

**Comment by egglestn** [comment]
There are several open source cookie consent helpers, I've used this one by osana, via the cdn: https://www.osano.com/cookieconsent

Would something like this work, or do we need to roll our own?

**Comment by aspiers** [comment]
@egglestn I can't think of any reason we would need to roll our own rather than reuse a standard approach.

**Comment by egglestn** [comment]
I will have a go with osana, let me know if anyone prefers a different one

**Comment by egglestn** [comment]
API link for future reference: https://www.osano.com/cookieconsent/documentation/javascript-api/
I use cookies inspector for chrome to make testing easier: https://chrome.google.com/webstore/detail/cookie-inspector/jgbbilmfbammlbbhmmgaagdkbkepnijn?hl=en

**Comment by egglestn** [comment]
PR: https://github.com/swapmyvote/swapmyvote/pull/75
- have sent screenshot to slack channel for review of colours and text

**Comment by aspiers** [comment]
Cookie consent code from #75 is now merged, plus I pushed some extra tweaks. I think it needs more styling, plus possibly an opt-out route - technically the current implementation doesn't ask for consent; it just notifies, and I'm not sure that's enough these days.  Does anyone else know?

**Comment by aspiers** [comment]
@tdg You're the data controller so you'll need to make the final decision on whether what we have is good enough.  Sorry ;-)

**Comment by aspiers** [comment]
Talked to @tdg at length about this and we think that after #101 we're decently covered on this.
