### ISSUE TITLE
Links from privacy policy to deletion from app and mailchimp

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#67]
This is required by GDPR.  We don't necessarily need to automate this - might be enough to explicitly state in the policy that people should email a certain address requesting removal from our database.  Then later if we find a lot of people requesting this, we could automate it.

**Comment by aspiers** [comment]
@tdg I think we can just update the privacy policy for now - can you do this?

**Comment by aspiers** [comment]
Actually this is already implemented so only needs to be linked to from the privacy policy.

**Comment by aspiers** [comment]
Ah no,  removal from mailchimp also needs to be linked from it.

**Comment by tdg** [comment]
If a user deletes themselves from the app, could it generate an email to us to delete them from Mailchimp too, as an MVP?

**Comment by tdg** [comment]
The other way for them to delete themselves from Mailchimp would be to click the unsubscribe link in any of our Mailchimp emails.

**Comment by aspiers** [comment]
Good points.  Is there a mailchimp unsubscribe URL we can include in the privacy policy?  I think that would be sufficient here.

**Comment by tdg** [comment]
> Good points. Is there a mailchimp unsubscribe URL we can include in the privacy policy? I think that would be sufficient here.

We can't really do this, as they could unsubscribe other people instead. Any Mailchimp email will have an unsubscribe link at the bottom that they can use, however, so I will note this in the privacy policy.

**Comment by egglestn** [comment]
I think this was covered under https://github.com/swapmyvote/swapmyvote/pull/87

**Comment by tdg** [comment]
Suggest we close this issue, @aspiers ?
