### ISSUE TITLE
Follow-up to PR 674 - automate election name changes

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#686]
Actually the "Thursday" mention does need fixing.  The others are nice-to-have but we can certainly live without.

_Originally posted by @aspiers in https://github.com/swapmyvote/swapmyvote/issues/674#issuecomment-1305362022_

**Comment by aspiers** [comment]
[As originally discussed](https://github.com/swapmyvote/swapmyvote/pull/674#discussion_r1015213656), the election might not be on a Thursday, but @baob pointed out:

> Seems pretty unlikely not to be though :). "Since 1918 a General Election has always been on a Thursday, except for 1918, 1922, 1924 and 1931. ". In the rare event that it is not, we can either automate the change or do it manually .
>
> https://theguardian.com/notesandqueries/query/0,5753,-2036,00.html

And [another comment](https://github.com/swapmyvote/swapmyvote/pull/674#issuecomment-1309318667) from @baob:

> By-elections, too, can be held on any day except a Sunday , although there have been only two since 1965 not held on a Thursday; Manchester Exchange in 1973 and Hamilton in 1978 (because the World Cup started on the Thursday), both on a Wednesday. Using Thursday is a convention, rather than a rule"

So I think we can close this for now.
