### ISSUE TITLE
Identification via phone number

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#7]
Allow log-ins from non-Facebook and Twitter sources, via a phone number that can receive a text verification code.

**Comment by tdg** [comment]
Ideally a voter could later add their other primary social/phone profiles more strongly to verify their identity to partners.

**Comment by aspiers** [comment]
After discussion we decided to keep Twitter/Facebook as initial login, and require phone verification later (e.g. before claiming a swap).

Seems there are a few options for how to do this, e.g.

- [heapsource/active_model_otp](https://github.com/heapsource/active_model_otp): Adds methods to set and authenticate against one time passwords (Two-Factor Authentication)
    - [Send code via Twilio SMS · heapsource/active_model_otp Wiki](https://github.com/heapsource/active_model_otp/wiki/Send-code-via-Twilio-SMS)
    - [SMS Pricing for Text Messaging - Twilio](https://www.twilio.com/sms/pricing/gb)
    - [Twilio SMS Ruby Quickstart - Send & Receive SMS - Twilio](https://www.twilio.com/docs/sms/quickstart/ruby)
- [How to Send SMS Messages with Ruby on Rails - Nexmo Developer Blog](https://www.nexmo.com/blog/2017/10/16/send-sms-ruby-on-rails-dr)

**Comment by aspiers** [comment]
@tdg said that https://www.messagebird.com/en/ are an SMS provider who’ve been supportive of other Forward Democracy projects and have been in touch and are interested in helping.  They seem to have [nice dev docs for Ruby](https://developers.messagebird.com/docs/verify/send-a-verification-token-ruby) too.

**Comment by aspiers** [comment]
https://stackshare.io/stackups/messagebird-vs-nexmo-vs-twilio

- Twilio is the most popular solution, and is [$0.09 per verification](https://www.twilio.com/authy/pricing) (that's pay-as-you-go, cheaper for bulk pre-pay)
- Nexmo seems to be next most (hah) popular, and is €0.05 per successful verification](https://www.nexmo.com/pricing)
- MessageBird is [£0.028 per outbound message to UK](https://www.messagebird.com/en/verify/) but maybe they'll give it to us for free.

**Comment by aspiers** [comment]
Am trying this out: https://developers.messagebird.com/tutorials/verify-ruby#sending-a-verification-code

**Comment by aspiers** [comment]
Just deployed #119 to staging which covers about 80% of the implementation.  Remaining items added to top of issue.

**Comment by aspiers** [comment]
Actually scratch that, I'm going to close this and file separate issues for the individual items.

**Comment by aspiers** [comment]
Separate issues found here:

https://github.com/swapmyvote/swapmyvote/labels/mobile%20verification
