### ISSUE TITLE
Prevent swaps with same party

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#70]
Currently you can select the same party for your preferred party *and* the one you're willing to vote for, both when logged in, and on the pre-login home screen.  We need some Javascript validation to prevent both, but also ideally some backend validation for the logged in case too.

In the logged in scenario, this is used as a "feature", as a way of allowing a user to indicate a desire to "deactivate" their account - explained in the FAQ at `/faq#deactivate`.  However we should replace that with a much better way of properly removing user accounts.

**Comment by DouglasLutz** [comment]
I can work on this

**Comment by aspiers** [comment]
Thanks Douglas, any help is hugely appreciated!  Although we do have
significantly more urgent issues on the project board right now if
you're not particularly attached to this one.

**Comment by DouglasLutz** [comment]
Sure @aspiers, I will try to help with other ones too

**Comment by aspiers** [comment]
I think this is much more urgent now there are only two constituencies.

**Comment by aspiers** [comment]
I've filed #466 for the pausing feature, so that we can address the immediate usability issue for BE2021 and not get bogged down with the functionality regression.
