### ISSUE TITLE
Substring search / auto-complete for constituencies

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#72]
As mentioned on https://github.com/swapmyvote/swapmyvote/issues/8#issuecomment-549415474, I think we need to change the existing constituencies dropdown to a text field which dynamically does substring search and autocompletion like [the one shown here](https://www.w3schools.com/howto/howto_js_autocomplete.asp).

Ideally this field would also accept postcodes as per #6.

**Comment by aspiers** [comment]
@georgecrawford Would you be able to take this one?

**Comment by georgecrawford** [comment]
Yep!
