### ISSUE TITLE
update privacy policy for GDPR

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#73]
The privacy policy is too lightweight to meet GDPR requirements, needs beefing up.

**Comment by tdg** [comment]
Clarify
- [ ] What info is shared from Facebook & Twitter to SMV (email, name)
- [ ] How we will use contact details in future for platform use
- [ ] how we will use contact details in future for news and other company objectives (opt in)

**Comment by tdg** [comment]
Places we store data to do with the project, which should be reflected in the policy:
(checked when done)

- [ ] Platform Databases (Heroku)
- [ ] System backups (Heroku & CMS)
- [ ] Email CRM
- [ ] Google Analytics (should be anonymised already)
- [ ] If you email us, on email servers
- [ ] On our team members' machines, where needed, for processing and backup

Any others @aspiers @georgecrawford ?

**Comment by aspiers** [comment]
Not sure but please cut and paste that checklist into the description at the top of this issue!

**Comment by egglestn** [comment]
Would this be useful? https://www.privacypolicies.com/blog/gdpr-privacy-policy/

If yes, I'm happy to pick up this one on Thursday, based on standard templates

**Comment by tdg** [comment]
@egglestn do you think we should have a very explicit description of what data the Application gathers and what it does with it, for example: 

> This Application collects some Personal Data from its Users including their voting preferences, constituency, name, profile picture, social network IDs, email address, and mobile phone number. 

> The Application uses the phone number and email address to authenticate you. It uses the email address to contact you about your vote swaps and vote swapping partners. At no time are your phone number or email address shown to anyone else. The other pieces of personal information help the Application to suggest prospective voting partners and help you and they to make a choice about who to swap with. In doing this the Application shows such prospective partners your stated voting preferences, constituency, profile picture, and the social network you used to log in. Part of your name is redacted and part of your name is shown with the aim of helping establish trust between voting partners.

**Comment by tdg** [comment]
> The Application stores some of your personal data on industry standard platforms including web and email servers. Access to these servers is strictly controlled with strong passwords and multi-factor authentication.

**Comment by tdg** [comment]
Personally identifying information is collected only for the purposes of providing the Application and is never shared with third parties. We use anonymised data in aggregate to monitor takeup of the Application and to discuss its political effect in public.

**Comment by tdg** [comment]
These should all be clarified in consent at point of data entry #74. 

> Clarify
> * [ ]  What info is shared from Facebook & Twitter to SMV (email, name)
> * [ ]  How we will use contact details in future for platform use
> * [ ]  how we will use contact details in future for news and other company objectives (opt in)

**Comment by egglestn** [comment]
@tdg I think adding explanatory information is always useful, and I like the texts you suggest. I would possibly change "redacted" to "hidden", imo it's a term that not everyone will know.

**Comment by tdg** [comment]
Thanks Sarah. Would you be happy to integrate my and your suggestions into one unified policy, and make a PR for it?

**Comment by aspiers** [comment]
@tdg I guess @egglestn is busy - maybe you can do it so I can focus on SMS verification?

**Comment by egglestn** [comment]
I ran out of Thursday, sorry - it was my last day in India, then on a plane on Friday, can pick it up tomorrow

**Comment by aspiers** [comment]
Oh OK great, thanks a lot @egglestn!! :-)

**Comment by aspiers** [comment]
@tdg Why are all the items in [this comment](https://github.com/swapmyvote/swapmyvote/issues/73#issuecomment-552150403) checked?  It says "(checked when done)" but AFAICS we haven't covered any of those yet?

I'm a bit concerned that by spreading the various todo items across multiple checklists in multiple comments that we're in danger of losing track and forgetting to cover one or more of them.  That's why I suggested cutting and pasting them all into the original description at the top of this issue.

**Comment by tdg** [comment]
By description, do you mean the first comment? 
Agree it would be best to have everything in one place. It also refers to various other GDPR issues so it was useful whilst amending those. 
Happy to try to pull this together later today if no further comment on substance from anyone

**Comment by tdg** [comment]
I'm integrating these and will create a PR for review

**Comment by tdg** [comment]
I've integrated the above into https://github.com/swapmyvote/swapmyvote/pull/86, 
but I'm not satisfied. 

Intend to use this as a template for further work on this
https://resources.workable.com/gdpr-privacy-policy-template

**Comment by egglestn** [comment]
Picking up this and separating privacy policy from cookie information, I'm not using this branch but will clone some of the text changes from it

**Comment by egglestn** [comment]
@aspiers I think we can't edit your initial comment, hence can't add the checklists there, but I will try and collect them all together somewhere

**Comment by aspiers** [comment]
> @aspiers I think we can't edit your initial comment, hence can't add the checklists there, but I will try and collect them all together somewhere

Ah OK thanks!

**Comment by aspiers** [comment]
@tdg I've merged all @egglestn's fabulous work on this, made some tweaks of my own, and deployed to both staging and production.  Please can you review the live text for the five pages listed under SMV in the footer and confirm you're good with this now?  Then I think we can resolve this one.

**Comment by tdg** [comment]
This is great and covers much of what we need to cover, as far as I can see

I have a few amendments, in this comment, and a few questions and additions, in the next. 

- [ ] Under 'Who we are and how to contact us' we should replace "hello@swapmyvote.uk" with "Forward Democracy Limited"

- [ ] Under 'Usage Data' and 'Tracking and Cookie Data' we say we will collect IP addresses. Can we make sure we aren't collecting these by using anonymised Google Analytics (#101)? (Also, we say under 'Analytics' that we don't.)

- [ ] "To be able to register to vote, UK citizens must be aged 16"… append "or 14 in Scotland"
Source: https://www.gov.uk/register-to-vote

**Comment by tdg** [comment]
Where does this bit come from? 

>Disclosure Of Data
Legal Requirements
We may disclose your Personal Data in the good faith belief that such action is necessary to:

>To comply with a legal obligation
To protect and defend our rights or property
To prevent or investigate possible wrongdoing in connection with swapmyvote
To protect the personal safety of users of the website or the public
To protect against legal liability

Could we beef it up so that we… 
- [ ] prepend and amend as follows:
We will not disclose your personal data to anyone beyond what is required for the provision of the service, unless such action is necessary to:

[List]

**Comment by tdg** [comment]
ADDITIONS as per 
https://github.com/swapmyvote/swapmyvote/issues/66#issuecomment-555109604

- [ ] Within eight weeks of an election result, we will anonymise all personal data relating to that election (removing name, email, and social media information) from our databases and delete backups from our records. We will retain anonymised data in perpetuity to facilitate study and public discussion of the effects of vote swapping.

**Comment by egglestn** [comment]
The Disclosure of Data section I reused from another website - we can and should change it as much as we like. @tdg suggest you open a new PR with these changes, they look sensible to me.
