### ISSUE TITLE
Establish informed consent at all points of data entry

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#74]
- [x] login

At `login` gather consent to store and share (part of) name (see #47), constituency, and voting preferences with potential voting partners. Necessary.
Link to Privacy Policy (see #73)  

- [x] confirm email address

At `confirm email address` (see also #15) gather consent to email user with necessary steps to confirm potential voting partners, and other necessary steps.
Also gather (optional) permission to 'email with infrequent news from Forward Democracy including press coverage, fundraising, and other products and initiatives to support, defend and extend democracy at this critical time'. 
Link to Privacy Policy (see #73)  

- [x] confirm mobile phone number

At `confirm mobile phone number` step, gather consent to store number and use it to send messages for security. 'This helps us ensure voting partners are genuine'. We may also use your number to alert you, for example if we think that your email is not being successfully delivered.

Also gather (optional) permission to 'I would like to receive infrequent SMS messages from Forward Democracy when new initiatives to support, defend and extend democracy are available'. 

Link to Privacy Policy (see #73)  

Please feel free to amend this description, or copy and paste in comments below.

**Comment by tdg** [comment]
@georgecrawford would you be happy to have a look at this with me?

**Comment by tdg** [comment]
- [ ] login
On clicking 'Swap My Vote!' a modal should appear with a button that says 'I agree':
> Swap My Vote can store my name, email address , social media ID and profile picture, constituency, and voting preferences to match me with possible vote swapping partners. 
> Privacy Policy [linked] 
"I agree" button - clicked takes the user forward. If not clicked, after a few seconds the button could vibrate to suggest action…

**Comment by tdg** [comment]
- [ ] confirm email address
At confirm email address (see also #15) 
>We will email you to confirm your email address, and with updates about possible vote partners. Would you also like us to email you with infrequent news from Forward Democracy? These emails will include other exciting initiatives to support, defend and extend democracy at this critical time, plus company news and highlights of press coverage. You can unsubscribe at any time from the footer of the email' 
"Yes please!" button
Link to Privacy Policy (see #73)

**Comment by tdg** [comment]
Description amended, superfluous comments deleted.

>**To decide**: _do we ever let confirmed voting partners have each other's phone number?_ (Probably not.)

This would be helpful for the user trust piece. Do we include another permission "to be able to be contacted solely by confirmed swap partners (you will confirm them before they can contact you)"?

**Comment by tdg** [comment]
Assigning @aspiers for help with decision making. 

@georgecrawford we have discussed the frontend impacts of this - have you had any further thoughts?

**Comment by tdg** [comment]
> > **To decide**: _do we ever let confirmed voting partners have each other's phone number?_ (Probably not.)
> 
> This would be helpful for the user trust piece. Do we include another permission "to be able to be contacted solely by confirmed swap partners (you will confirm them before they can contact you)"?

Decided not to ask for permission for phone to be shared, email to be shared at M0

**Comment by tdg** [comment]
Review and file separate issues for these
>Decided not to ask for permission for phone to be shared, email to be shared at M0

**Comment by aspiers** [comment]
Discussed with @tdg and we agreed:

1. not to track consent issues for features we haven't implemented yet
2. the existing text in the UI should be enough to establish informed consent, and even if it's not everywhere, the privacy policy should catch any remaining cases.
