### ISSUE TITLE
Make Facebook login button compliant (8.3)

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#76]
![Screen Shot 2019-11-11 at 21 47 32](https://user-images.githubusercontent.com/95868/68623811-3f001c00-04cd-11ea-8bfc-7bd5b246d649.png)![Screen Shot 2019-11-11 at 21 45 03](https://user-images.githubusercontent.com/95868/68623840-4f17fb80-04cd-11ea-896d-2159c2c5fd94.png)

**Comment by aspiers** [comment]
Seem to be two issues here:

- [ ] Some kind of domain mismatch in the app settings even though it looks fine to me
- [ ] Apparently they don't like our login button

This could turn into an urgent issue since when we think we've resolved both, we have to resubmit to facebook for review, and that might take a while.  So if we don't get ahead of it then it could delay launch.  And I'm busy this week so probably can't work on it.  @tdg Can you try to ensure that someone else is progressing this so that we get ahead of any potential delays?

**Comment by tdg** [comment]
> [ ] `Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.` Don't know why as it looks fine to me (currently both swapmyvote.uk and [www.swapmyvote.uk](http://www.swapmyvote.uk) are listed)

Weirdly, neither seemed to be, so I have added them back in now…

**Comment by tdg** [comment]
> * [ ]  Apparently they don't like our login button

@georgecrawford would this be something you might be able to help with? I suspect it is a simple case of updating the 'login with facebook' style to their new brand guidelines

**Comment by tdg** [comment]
I've turned on 'Enforce Https'

**Comment by tdg** [comment]
The Facebook SDK for JavaScript doesn't have any standalone files that need to be downloaded or installed, instead you simply need to include a short piece of regular JavaScript in your HTML that will asynchronously load the SDK into your pages. The async load means that it does not block loading other elements of your page.
The following snippet of code will give the basic version of the Facebook SDK for JavaScript where the options are set to their most common defaults. Insert the following code snippet directly after the opening <body> tag on each page you want to use Facebook Analytics. Replace {your-app-id} with the App ID and {api-version} with the version of the API you are targeting. The current version is v5.0.

`
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{api-version}'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>`

**Comment by tdg** [comment]
The first step when loading your web page is figuring out if a person is already logged into your app with Facebook login. You start that process with a call to FB.getLoginStatus. That function will trigger a call to Facebook to get the login status and call your callback function with the results.
Taken from the sample code above, here's some of the code that's run during page load to check a person's login status:
```
FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
});Copy Code```
The response object that's provided to your callback contains a number of fields:
```
{
    status: 'connected',
    authResponse: {
        accessToken: '...',
        expiresIn:'...',
        signedRequest:'...',
        userID:'...'
    }
}Copy Code```

status specifies the login status of the person using the app. The status can be one of the following:

- connected - the person is logged into Facebook, and has logged into your app.
- not_authorized - the person is logged into Facebook, but has not logged into your app.
- unknown - the person is not logged into Facebook, so you don't know if they've logged into your app or FB.logout() was called before and therefore, it cannot connect to Facebook.
- authResponse is included if the status is connected and is made up of the following:
- accessToken - contains an access token for the person using the app.
- expiresIn - indicates the UNIX time when the token expires and needs to be renewed.
- signedRequest - a signed parameter that contains information about the person using the app.
- userID - the ID of the person using the app.

Once your app knows the login status of the person using it, it can do one of the following:
If the person is logged into Facebook and your app, redirect them to your app's logged in experience.

If the person isn't logged into your app, or isn't logged into Facebook, prompt them with the Login dialog with FB.login() or show them the Login Button.

**Comment by tdg** [comment]
**4. Add the Facebook Login Button**

Including the Login Button into your page is easy. [Visit the documentation](https://developers.facebook.com/docs/plugins/login-button) for the login button and set the button up the way you want. Then click Get Code and it will show you the code you need to display the button on your page.

The `onlogin` attribute on the button to set up a JavaScript callback that checks the login status to see if the person logged in successfully:
```
<fb:login-button 
  scope="public_profile,email"
  onlogin="checkLoginState();">
</fb:login-button>Copy Code
This is the callback. It calls FB.getLoginStatus() to get the most recent login state. (statusChangeCallback() is a function that's part of the example that processes the response.)
function checkLoginState() {
  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });
}
```

**Comment by tdg** [comment]
In short, it looks like they've given us the steps we need, but I'm not best placed to implement them, if someone can help pick up.

**Comment by georgecrawford** [comment]
> > * [ ]   Apparently they don't like our login button
> 
> @georgecrawford would this be something you might be able to help with? I suspect it is a simple case of updating the 'login with facebook' style to their new brand guidelines

Yep, I can take a look at this.

**Comment by aspiers** [comment]
Cool thanks a lot @georgecrawford !

**Comment by aspiers** [comment]
I'm splitting this issue in two - will file another bug regarding 8.1 but I suspect that was caused by a redirect loop which I caused a while back and which we quickly fixed.

**Comment by aspiers** [comment]
@georgecrawford can't look at this after all, so we need to find someone else.

**Comment by aspiers** [comment]
@threedaymonk Any chance you could take a look at this? It's super urgent right now.

**Comment by threedaymonk** [comment]
Not until Monday, I'm afraid: I'm at a practice this afternoon and playing at an event tomorrow. And I'm probably not best placed to look at this as I don't have a Facebook account!

**Comment by aspiers** [comment]
OK no worries!  I think we may have found someone else to work on this.  Whoever starts on it first, please comment on this issue so we can coordinate efforts effectively.

**Comment by jpallen** [comment]
I'm looking at updating the login button to Facebook's new 2019 branding

**Comment by aspiers** [comment]
Brilliant, thanks so much!

**Comment by jpallen** [comment]
I'm hoping that the PR at https://github.com/swapmyvote/swapmyvote/pull/137 will be enough to fix 8.3 - Facebook rebranded recently, and I guess they're getting on top of everyone to update their external use of their branding. It uses their new logo and colours at least.

**Comment by aspiers** [comment]
@jpallen https://developers.facebook.com/docs/facebook-login/web/login-button seems to suggest that compliant buttons should say "Continue with Facebook" but ours says "Log in with Facebook".

**Comment by aspiers** [comment]
Also the font, padding, and border rounding are all a bit different.  So I suspect we really need to use the SDK here.

**Comment by tdg** [comment]
> @jpallen https://developers.facebook.com/docs/facebook-login/web/login-button seems to suggest that compliant buttons should say "Continue with Facebook" but ours says "Log in with Facebook".

I was just looking at that too, but there is a `Button Text` dropdown that allows for 'Login with Facebook', too 

The code generated says

Step 2: Include the JavaScript SDK on your page once, ideally right after the opening body tag.
```
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0&appId=377810399053422"></script>```

Step 3: Place this code wherever you want the plugin to appear on your page.

```
<div class="fb-login-button" data-width="" data-size="large" data-button-type="continue_with" data-auto-logout-link="false" data-use-continue-as="false"></div>```

**Comment by aspiers** [comment]
Yeah, I just found that.  These steps look super easy - I'll do it in the morning.

**Comment by aspiers** [comment]
Well putting the code in is easy, but getting it working ... :-/

**Comment by aspiers** [comment]
One problem is that the new button from the SDK requires https, which means setting up a local ngrok or pagekite or other SSL termination proxy, but that in turn requires the resulting URL to be configured in the test app :man_facepalming:

**Comment by aspiers** [comment]
https://developers.facebook.com/docs/facebook-login/best-practices#button says

> ## 2. Design: Use a Large, Rectangular Button
> 
> Use large, rectangular buttons for Facebook Login that are adjacent to other sign options. Facebook Login will do better if it is shown ahead of other options. You also want buttons to be consistent with the rest of your app design as buttons that are significantly visually different (for example, small, round buttons) won't perform as well.
>
> The Facebook Login button that comes with our SDKs is easy to integrate and includes built-in education that ensures a consistent design and experience. However, if you do decide to build your own, for best results follow the Facebook Platform Policy and the recommendations in the User Experience Design topic.

so it seems that it's OK to build our own button.

I'm currently trying to figure out whether the Javascript SDK is usable, but suspect it might not be.  But it's clearly not required, because https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow says:

> ## Manually Build a Login Flow
>
> The easiest and quickest way to implement Facebook Login is with our official SDKs for JavaScript, iOS, and Android. We recommend you follow our separate guides for these platforms.
> 
> However, if you need to implement browser-based login for an app without using our SDKs, such as in a webview for a native desktop app (for example Windows 8), or a login flow using entirely server-side code, you can build a Login flow for yourself by using browser redirects. This guide will take you through each step of the login flow and show you how to implement each one without using our SDKs:

**Comment by aspiers** [comment]
OK, I found https://developers.facebook.com/docs/facebook-login/userexperience#buttondesign which explicitly proves that Facebook is much more lenient than I first thought.  They don't even *require* a particular color but they recommend #4267B2 which we are not currently using.  I'll fix that.  The only hard requirement seems to be to use an official "f" logo which @jpallen's recent PR already took care of.  The rest are just recommendations.

**Comment by aspiers** [comment]
Hah, they're even confused themselves.  https://developers.facebook.com/docs/facebook-login/userexperience#buttondesign says:

> ## Copy
> If you're using Facebook Login to enable account creation and login, recommended labels are "Continue with Facebook" or "Login with Facebook".

but the button generated with the official JS SDK reads "Log in with Facebook" (notice the extra space).

**Comment by aspiers** [comment]
Not only that, but their official JS SDK button uses #1877f2!!  If they're that confused, they shouldn't have grounds to moan about us...

**Comment by fkorning** [comment]
apologies if I'm out in left-field, but might it have to do with CORS cross-origins?

**Comment by aspiers** [comment]
I don't think so - think it's probably simply that we were using an out of date fb logo ... In any case I'm pretty sure we're compliant now.
