### ISSUE TITLE
BUG: test database setup - can make developer (rspec) testing impossible

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#763]
There's no simple way to re-create the test database. I discovered this after accidentally causing huge numbers of test to fail by running seeds against the test DB.

What should work, by convention, is

    RAILS_ENV=test rake db:seed
    
Actually, after that lots of tests fail and you need to spot what tests are failing due to unexpected extra table rows in the test DB, and then empty  those tables. From memory, emptying 3 or 4 tables this way will do it.

@aspiers you're probably the only one affected by this right now.

**Comment by aspiers** [comment]
What's the cause of this, and what's your workaround?

**Comment by baob** [comment]
> What's the cause of this, and what's your workaround?

The trigger for this could be anything that writes unwanted table rows to the test db. Like developer error. May also affect someone setting up and new test DB.

Underlying cause is probably that we have seed scripts that don't take into account the differing needs for for test. E.g. for our current suite of tests it appears some tables must be empty in the test environment

Workaround is in the first comment (description)

> after that lots of tests fail and you need to spot what tests are failing due to unexpected extra table rows in the test DB, and then empty those tables.

**Comment by baob** [comment]
I may have misunderstood the conventions -> https://stackoverflow.com/questions/55270463/how-to-automatically-migrate-the-development-and-test-databases-with-rails-dbm

**Comment by baob** [comment]
Closed by #777
