### ISSUE TITLE
BUG: password reset seems broken on staging

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#771]
- tried to register -> "email is already registered"
- tried to sign in -> "password or email not matched"
- tried to reset password and I got this

<img width="744" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/83822a92-8958-4fb7-bd4b-d01f96ed9af5">

**Comment by aspiers** [comment]
@baob Do you still see this?  Seems fine to me.

**Comment by baob** [comment]
Cannot reproduce.
