### ISSUE TITLE
Add imprint to site

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#787]

**Comment by aspiers** [comment]
@tdg Sorry for the stupid question, what is this one about?

**Comment by aspiers** [comment]
Found it in Zulip: https://forwarddemocracy.zulipchat.com/#narrow/stream/328997-SMV-frontend/topic/imprint

Looks like we need to add this, but to every page or just some?

> Published and promoted by Tom de Grunwald on behalf of Swap My Vote, a campaign name of FORWARD DEMOCRACY LIMITED registered at 100 Church Street, Brighton, BN1 1UJ. Registered company in England & Wales no. 11707599.

**Comment by tdg** [comment]
Every page in the far footer I think

Cf bestforbritain.org
