### ISSUE TITLE
Change seeding to enable testing from RW personas

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#793]
Idea came up when discussing https://github.com/swapmyvote/swapmyvote/issues/773 - the more LW campaigns we integrate, the less we look like an unbiased site, we should also test the site using RW personas.

Right now, the seeding of the test database doesn't create any suitable RW swaps.

Needs to be built on the branch for PR #801

**Comment by tdg** [comment]
I'm seeing what else I can source and have reached out to https://www.scotlandinunion.co.uk/ for a csv, will revert with and RW sites I find too

**Comment by baob** [comment]
Not needed now, addressed by PR #862
