### ISSUE TITLE
Password validation is turned off

### ISSUE THREAD

**Issue by stevebaxter** [swapmyvote/swapmyvote#797]
We're not requiring a password for users that sign up with email, if they do provide a password we're not checking the password and validation match. The reason seems to be it's turned off here:

https://github.com/swapmyvote/swapmyvote/blob/master/app/models/user.rb#L367

Turning this on causes a load of test failures, so not something we can just enable.

**Comment by baob** [comment]
Looks like that was initially introduced with this commit

commit 2c2f4a3efbeb57a756a0b5155ab6ab438a3d9f1e  
Author: James Allen <james@jpallen.net>
Date:   Thu Nov 28 15:34:06 2019 +0000

    Hook up Devise for email log ins
    
And then other commits move the method around a bit,

So maybe devise is supposed to take over that functionality ?

**Comment by stevebaxter** [comment]
If you change the line above to true it all works, but lots of tests fail because we're not specifying a password in the tests. So I guess we need to turn it on and fix the tests, or find a way of turning it off just for tests?

**Comment by baob** [comment]
@stevebaxter If you push your branch somewhere public, I can change the function and have a go at fixing the tests ... and raise a PR back into your branch if successful ?

**Comment by stevebaxter** [comment]
It's just changing that function I think. Would be great if you could look, I don't know all that much Ruby!

**Comment by baob** [comment]
Unassigning myself. I take responsibility for the PR #797 (that changes the return from the function), but I don't know exactly what @stevebaxter found that led to asking for that change.

**Comment by stevebaxter** [comment]
Without your changes you can sign up with email and an empty password, or with a password and password validation that don't match. That's what we need to test.

**Comment by aspiers** [comment]
@baob This can be closed now that #804 is merged, right?  I will do more of my own testing soon BTW.

**Comment by baob** [comment]
I haven't actually checked the thing steve said was broken ... hold on

**Comment by baob** [comment]
According to @stevebaxter 's criteria, this is fixed
