### ISSUE TITLE
Clarify names for constituencies and match against ONS ID

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#8]
Move to a better source of data about constituency names and/or make it easier for users to find their constituency (currently unclear which this issue is about).

**Comment by tdg** [comment]
https://github.com/simonwibberley/map-to-constituency-id

**Comment by baob** [comment]
'Better' implies something wrong with the old one. What exactly are we trying to improve ?

**Comment by aspiers** [comment]
Did you mean to paste something in to your last comment?

**Comment by aspiers** [comment]
@tdg this needs more clarity

**Comment by baob** [comment]
> Did you mean to paste something in to your last comment?

Correct. My bad. I meant to post this link to the source:  https://github.com/swapmyvote/swapmyvote/tree/master/db/fixtures

**Comment by tdg** [comment]
I've edited the name to try to make this clearer. Basically in 2017 users (voters) were looking for their constituency from a drop down list. 

So some would look for East Renfrewshire but not find their constituency Renfrewshire East (indicative example)

We need the canonical list and a way to clarify ambiguities

**Comment by tdg** [comment]
Is this helpful? 
https://docs.ropensci.org/PostcodesioR/index.html

**Comment by aspiers** [comment]
>Is this helpful?
>docs.ropensci.org/PostcodesioR/index.html

No, that's for R not Ruby.

@tdg I think there are two separate issues being conflated here:

1. Make sure we have an accurate list of constituencies.
2. Make sure the user can find their own constituency easily in the UI.

Regarding 1., so far I have not heard anything which suggests our current list is inaccurate.  Having East/West/North/South before or after the place name doesn't seem like an inaccuracy to me.  Are you aware of any genuine inaccuracies?  If not then we don't need a new data source.

Regarding 2., whether our canonical list has East/West/North/South before or after the place name, there will always be users who expect it to be the other way around, so we need to ensure the UI allows them to find it easily regardless of which way around it is.  I can immediately think of two separate possible solutions to this:

a) List each constituency containing East/West/North/South twice, once with the directional word first, and once with it last.
b) Replace the dropdown with a substring search form like [the one shown here](https://www.w3schools.com/howto/howto_js_autocomplete.asp).

Frankly I think b) is much better.  So please let me know if you think that is sufficient, or if we also really need to change the list to a different source.

**Comment by aspiers** [comment]
Also, it's better to keep the issue titles short and snappy so they fit nicely on the GitHub Project cards and in email Subject headers ;-)  However you can edit the issue description to put more detail into that at any time.

**Comment by tdg** [comment]
Good points. on -

>1. Make sure we have an accurate list of constituencies.

I can't remember the exact places people had issues with, but there were quite a lot of constituencies that had more than one name, not just because of cardinal directions but other patterns like `TownA & TownB` also being known as `TownB & TownA` (eg). It wasn't a fault of the data so much as the user need you articulate:

>2. Make sure the user can find their own constituency easily in the UI.

Autocomplete would meet the user need here, but we also have #6 for this. An autocomplete field could be a useful backup method, but I suspect #6 is a better strategy overall, on its own.

**Comment by aspiers** [comment]
Good point, I think we need both.

**Comment by baob** [comment]
> patterns like TownA & TownB also being known as TownB & TownA 
I've seen mismatches like this and more when comparing constituency names from 2 sources. Doing that in an automated fashion, without a canonical name or ID, is a nightmare.

**Comment by baob** [comment]
Can I propose we switch to this as a source ?

https://opendata.camden.gov.uk/Maps/National-Statistics-Postcode-Lookup-UK/tr8t-gqz7

I can:
1) Take a manual copy and commit it.
2) Build a (replacement) constituency table from it
3) Perhaps automate (not schedule) the download with rake (may be overkill, as it updates every 3 months) 
4) go on to work on issue #6 based on the same data.

**Comment by aspiers** [comment]
Sounds good to me @baob, thanks!  I'm guessing we want a single field which accepts either postcode or constituency - right?  And I'm pretty strongly in favour of that allowing substring search on constituencies (not substring search on postcodes though).

**Comment by baob** [comment]
New plan based on canonical data source: https://geoportal.statistics.gov.uk/datasets/westminster-parliamentary-constituencies-december-2018-names-and-codes-in-the-united-kingdom
1) Take a manual copy and commit it.
2) Build an alternate constituency table from it (say ons_constituencies) (pure ruby, tested)
3) establish link between existing constituency/polling data table and new ons table
4) update rake db:seed to simply call the tested code

**Comment by baob** [comment]
> establish link between existing constituency/polling data table and new ons table

This step still outstanding. Have started on it. Tedious business of matching by name.

**Comment by tdg** [comment]
Does this help? 

Best for Britain MRP estimates, reverse engineered by Chris Hanretty https://docs.google.com/spreadsheets/d/1Vf2iQOKjc6Lk7tTcTpRgEFFLIV-GoTIpj9ldtg8400k/edit#gid=1377832468
via https://twitter.com/chrishanretty/status/1191349243828670464

**Comment by aspiers** [comment]
I've submitted #72 for improving the UX side of things.  Have chatted with @tdg and we suspect that while this issue is definitely valuable longer-term, there are more urgent issues right now, unless @baob you have discovered any serious issues with the existing constituency list so far?

**Comment by baob** [comment]
@tdg @aspiers 

So long as you don't want users to enter their postcode to find their constituency ( https://github.com/swapmyvote/swapmyvote/issues/6 ) , there is only one problem with continuing with the current constituency table ... it is missing 28 constituencies. 

If you want to do postcode lookup, then, since the current table has no commonly used ID (it only has a name that in many cases does not match the ONS standard name, and  it does not have the ONS id), then someone will need to do a name-matching exercise, our constituencies against the constituency names in the incoming postcode list. 

The branch I have in progress is nearing the point where both constituency tables can be matched on a 'normalised' name ... only 25 mismatches left (started at something like 150) 

Postcodes and matching aside, we still have to discover which 28 are missing from out table, and we may need to continue my matching exercise to do that.

**Comment by aspiers** [comment]
Maybe a stupid question but can't we scrap the existing incomplete list and just use the new one?

**Comment by baob** [comment]
Perfectly reasonable question which I didn’t think to address, sorry. The current table has polling data . So long as there is no need to maintain linkage with the polling data, we can use the new table when asking users for their info, which should be much easier to link To postcodes via the ONS Id

**Comment by tdg** [comment]
We will need to link to polling data, but this (reverse engineering of the big MRP recently by Chris Hanretty) polling data has ONS IDs too. 

https://docs.google.com/spreadsheets/d/1Vf2iQOKjc6Lk7tTcTpRgEFFLIV-GoTIpj9ldtg8400k/edit#gid=1377832468

via https://twitter.com/chrishanretty/status/1191349243828670464

**Comment by tdg** [comment]
Hmm, that doesn't have 650 seats in it (565). I think NI and Scotland are missing. That still doesn't seem to add up, though.
The Electoral Calculus polls have Scotland but no NI (and yet 555). Ditto.
Traditionally, FYI, SMV hasn't covered NI because it's such a different situation. 
Sorry if this has _not_ helped…

**Comment by baob** [comment]
It's all down to timing, resources, priorities.

For this story/ticket, _I think_ nothing else needs to be done. New data is there in a table, but unrelated to any other table. It's only if you want to change the UX for users identifying their constituency (without adding postcodes) that more happens here. 

I'll comment more on the postcodes ticket, https://github.com/swapmyvote/swapmyvote/issues/6

**Comment by baob** [comment]
Okay, having seen a bit more of the codebase now, here's my summary of what should happen next WRT to this ticket.

1) We should, in the code where users generate their profile, swap out the old constituencies table and start using the new one. New one needed because it has all the constituencies, and it has ONS id for linking to other stuff (e.g. postcodes, MP candidates, polls etc). THIS IS NEEDED FOR LAUNCH, specifically, before users start signing up. If we don't do it for launch, we'll face the task of either (a) Getting all the candidates to go back to their profile and provide a constituency or (b) do the job of matching old constituency table to new constituency table by constituency name, which will be a bit of a fudge, but it can be done.

2) Doing that change will mean we break the existing link with the polling data. If we need to fix that, I suggest we start another issue on this repo.

**Comment by aspiers** [comment]
I've commented on #9 about the new strategy we decided yesterday for obtaining data based on ONS ID which can be used to better inform users' swap decisions.

**Comment by aspiers** [comment]
@baob Now that I merged #143, is this done?

**Comment by baob** [comment]
So long as 'user selects constituency by postcode' is covered elsewhere, yes, this is done.

**Comment by aspiers** [comment]
[**@baob**](https://github.com/baob) commented on [November 26, 2019 11:02 PM](https://github.com/swapmyvote/swapmyvote/issues/8#issuecomment-558854607 "2019-11-26T23:02:33Z - Replied by Github Reply Comments"):
> So long as 'user selects constituency by postcode' is covered elsewhere, yes, this is done.

That's covered by #6, so I'm closing - yay!  Congrats on your awesome work so far!

**Comment by tdg** [comment]
Well done @baob - amazing stuff!
