### ISSUE TITLE
API documentation doesn't mention SNP

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#805]
Let's add `snp` to the list (assuming it's available)

**Comment by tdg** [comment]
Do we also add Plaid Cymru?

**Comment by tdg** [comment]
If we do indeed still support `ukip` is it time to deprecate

**Comment by baob** [comment]
Plaid and SNP are supported by the API, just not mentioned explicitly ( "snp", "plaid_cymru") easy to add those.

UKIP have 27 candidates this time, let me know what you want to do ?

**Comment by tdg** [comment]
Let's remove ukip entirely from the site, they had their time
