### ISSUE TITLE
Include link to aggregated tactical recommendations

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#81]
https://www.livefrombrexit.com/tacticals/
Is the best laid out of these I've seen yet. 

Include link (or actual data) on prospective partner profile (next to polls) 

Data is available from here, and is updated every 4-6 hours
https://www.livefrombrexit.com/tacticals/data/recommendations.json

**Comment by egglestn** [comment]
What's the vote, do we just include the link? Or go for the data feed?

**Comment by tdg** [comment]
> go for the data feed?

This :)

**Comment by tdg** [comment]
Clarified and superseded by #161
