### ISSUE TITLE
facebook sharing seems broken

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#830]
For example, the welcome email contains:

> [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.swapmyvote.uk&sdk=joey&display=popup&ref=plugin)

which doesn't seem to work at all.

**Comment by aspiers** [comment]
Or maybe there are others we could ask for help with simple stuff like this?

**Comment by tdg** [comment]
![image](https://github.com/swapmyvote/swapmyvote/assets/95868/e3fd9b84-9497-4d07-99db-b46522699fef)
I clicked the link from the GitHub comment above and it opened a dialog as I would expect.. will check email too

**Comment by tdg** [comment]
It worked from my welcome email too

**Comment by aspiers** [comment]
Oh cool thanks, in that case maybe it's my cookie blocker or something like that!

**Comment by aspiers** [comment]
Although it would be best to test from a Facebook account which isn't an admin of the SMV app, just to make sure it's working for normal users.

**Comment by tdg** [comment]
True although I don't think the sharer protocol needs any privileges - but always good to double check

**Comment by aspiers** [comment]
OK weird, working for me too now.  Closing.
