### ISSUE TITLE
TV import constituency fix: Scotland in Union

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#866]
@tdg It would be handy if you could contact Scotland In Union and ask
* are there any updates ?
* if so can they correct the constituency names

If they aren't doing any updates for the parties, selected, I can make the changes on our side.

(following suggestion here: https://github.com/swapmyvote/swapmyvote/issues/834#issuecomment-2190207736)

Constituencies are expected to match this dataset: https://pages.mysociety.org/2025-constituencies/datasets/parliament_con_2025/0_1_4 

From memory, these are the corrections:

* Constituency lookup failed for {:mysoc_name=>"Dunbartonshire West", :advice=>"Labour"}. -> West Dunbartonshire
* Constituency lookup failed for {:mysoc_name=>"Kilmarnock and Loudon", :advice=>"Labour"}. "Kilmarnock and Loudo**u**n"
* Constituency lookup failed for {:mysoc_name=>"Renfrewshire East", :advice=>"Labour"}. -> East Renfrewshire

**Comment by tdg** [comment]
No updates from Scotland in Union (and unlikely to be)

**Comment by tdg** [comment]
Just so I know, are we aiming to launch with Scotland in Union info integrated?

**Comment by baob** [comment]
Yes, but the minor fix referenced here has not been done yet.

**Comment by baob** [comment]
Closed by merge of #917
