### ISSUE TITLE
Integrate data and predictions from opinion polls

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#9]
Integrate a regularly and automatically updated sources of predictions from opinion polls.

**Comment by tdg** [comment]
See also #8

**Comment by aspiers** [comment]
We don't want to get into the business of aggregating opinion polls or holding data on them, so this should be mostly a question of delegating or using available APIs.

**Comment by tdg** [comment]
We will probably continue to use https://www.electoralcalculus.co.uk/orderedseats.html as a source. We need to remember to update it - we'll be prompted by EC's email alerts however

**Comment by aspiers** [comment]
This isn't entirely easy until it's made more clear exactly what needs to be done.

**Comment by aspiers** [comment]
I think @tdg, @baob and I managed to clarify this yesterday.  We're gonna switch to using https://www.livefrombrexit.com/tacticals/data/recommendations.json as soon as #8 is resolved, or perhaps at the same time as resolving it.

**Comment by baob** [comment]
Time to clarify requirements, @tdg @aspiers ... how much of this do we actually need to show on SMV ?

I can see some obvious ones, 
* recommendation site (maybe 6-8 entries, best 4 britain etc)
* recommendations, keyed by constituency ons id and recommendation site. And containing links to our parties

![image](https://user-images.githubusercontent.com/55932/69492909-09313f00-0ea0-11ea-82a4-137af4054659.png)

**Comment by aspiers** [comment]
Just merged #173.  @baob I think you had another branch up your sleeve which adds the recommendations to the frontend, right?  I'm ready for that now!

**Comment by baob** [comment]
I did start on one, but subsequent edits to the that view or the CSS wrecked the display completely  so I reverted it.  https://github.com/baob/swapmyvote/commit/2e1506f8de16237dd2597c99881c0a6b55e4bbda

Now covered by this ticket --> https://github.com/swapmyvote/swapmyvote/issues/81 and this ticket https://github.com/swapmyvote/swapmyvote/issues/161 ... I think

**Comment by aspiers** [comment]
OK well feel free to submit a draft PR - even if it totally balls up the display we have frontend guys who could work on that if you prefer not to :grin:

**Comment by aspiers** [comment]
I think we got confused somewhere along the way - this issue is somewhat vague but was originally about opinion polls not tactical recommendations, which is covered separately in #161.  I just merged #178 which I think closes both this and #154.
