### ISSUE TITLE
Willing Party profile

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#905]
Whenever a voter sets or changes
* the party they are willing to vote for
* their constituency

take then to a page that shows them how their profile will look to potential swappers, and ask them to confirm their choice.

**Comment by tdg** [comment]
Can we refine this so it is framed as how the voter's profile will _work_ for PVPs, ie not how it will _look_ (this could get confusing and has an empathy cost).

**Comment by aspiers** [comment]
Somewhat related:

We already know that it's possible to change preferred/willing/constituency even when a user has already confirmed a swap (in which case the swap is automatically cancelled), with the exception of on election day when we're in `open-and-voting` mode.  However I noticed earlier that the site doesn't require much in the way of "are you really sure? this will cancel your current swap" confirmation when the user makes this change.  There is copy warning of the consequences, but a more prominent confirmation might be helpful.

The reason I see this as related is that we may want to consider an intermediary "preview" page where the user _previews_ a change of preferred/willing/constituency and how it will work (to use @tdg's words) for PVPs, _before_ the change is actually confirmed.  So then the loud confirmation request would be part of the same preview page.  IOW: "Here's the effect your change would have, are you sure you want to go ahead with it?"

That said, this all sounds a bit complex and I'm not sure we have time for it.

**Comment by baob** [comment]
@tdg @aspiers Any thoughts on the wording here ? This is just a quick rough idea from me, I'm sure it could be improved.

<img width="989" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/12135ef6-7a55-4ccc-96fe-b72fac11e464">

**Comment by baob** [comment]
And this is the choice of buttons at the bottom of the page.
<img width="647" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/afdab0cd-2027-4136-b1a8-9159b0024e81">

**Comment by tdg** [comment]
As a feature, I think it's great.
As an example, it's an amusing choice (but a suitably absurd one).
As copy, it's a good first draft. Second draft, I suggest:

This is how the vote swap you're offering will appear for potential voting partners. 
The party you are willing and offering to vote for in your constituency can have a strong affect on your swap options.
If you are happy to offer to swap a vote for other parties, it can sometimes improve your swap options. 

In emphasised and red-highlighted background*
Do you want to proceed with this party, or change your offered vote?
 
Buttons:
Swap My Vote 
Change My Swap

*one for our UX experts?

**Comment by baob** [comment]
Are you sure about 
```
Buttons:
Swap My Vote
Change My Swap
```
Both pieces of text could be construed as 'go back and change what I'm offering' couldn't they ?

**Comment by tdg** [comment]
Fair point, try something else (aim for three words if possible)

**Comment by tdg** [comment]
Or: 
Do you want to proceed with this party, or change your offered vote?

Buttons:
Proceed
Change

**Comment by baob** [comment]
This is how it looks now. No red colouring ... I think @stevebaxter will know the right way to style this for emphasis without explicitly setting text to red. 

![image](https://github.com/swapmyvote/swapmyvote/assets/55932/8f2ae095-aa69-48d9-bb66-04381e3ceccb)

**Comment by tdg** [comment]
The buttons are great and the copy is long - more like a tooltip text?

If it could be somehow expanded, the copy could just say

This is how you will appear to vote swap partners (i)

Do you wish to proceed?

Proceed / Change

**Comment by baob** [comment]
> more like a tooltip text?
> 
> If it could be somehow expanded,

Hmm, not sure I could do that without some impact on accessibility ... might be better to get @stevebaxter on that one.

**Comment by tdg** [comment]
For sure. Even a little expanding triangle for unfolding a bit of page would be okay. But I wonder if we start without the long explanation and look to add it back in?

**Comment by baob** [comment]
@tdg Problem with the text as it stands, is that there is nothing to explicitly tell you what willing party you chose. Since part of the motivation for this was to ensure people have not misunderstood willing and preferred, we might want to include that in the text somehow.

**Comment by tdg** [comment]
I tend to think that the short copy would be enough of a nudge to see if it helps make a difference - and help generally with the onboarding approach

**Comment by aspiers** [comment]
@baob Just talked with @tdg and we think we should not have both new text at the top _and_ the existing interpretation text as seen by the user's PVPs as that would be an overwhelming amount of text and require too many mental hurdles to understand.

Instead we think we can just make a copy of https://github.com/swapmyvote/swapmyvote/blob/master/app/views/user/swaps/_polls_advice.html.haml specifically for this new page, keep the exact same conditionals, and only tweak the text to explain the impact of the current user's choice of preferred on the likelihood of them being picked for swaps.

**Comment by aspiers** [comment]
e.g. something like

```haml
  - if poll.marginal_score < 1000
    - lead_trail = poll.signed_marginal_score.positive? ? "leading" : "only trailing the leading party"
    &#x2B50; Looks like your vote could make a difference for
    = party.name
    which is
    = lead_trail
    by
    = percent_score
    in the polls, so it's more likely that people supporting
    = party.name
    will want to swap with you.
  - elsif poll.signed_marginal_score.positive?
    Looks like your vote may be supporting a safe win for
    = party.name
    which is currently leading by
    = percent_score
    in the polls, so it's less likely that people supporting
    = party.name
    will want to swap with you.
  - else
    = party.name
    is trailing by
    = percent_score
    in the polls and may still lose despite this swap, so it's less likely that people supporting
    = party.name
    will want to swap with you.
```

**Comment by baob** [comment]
So, you want that to replace the entire page content, apart from the buttons ?

**Comment by aspiers** [comment]
I don't think we've fully figured it all out yet.  Maybe this was a bit presumptious:

> we think we should not have both new text at the top and the existing interpretation text

I can imagine two possibilities:

1. Move the interpretation text (which would be along the lines I just suggested) to the top
2. Keep it where it is, and have a simple sentence at the top explaining the point of this new page, e.g. "Your current choice to vote for $WILLING results in the following:"

I suggest the first step is to to produce the new version of the interpretation text as suggested above in the same place it currently is, then see how it looks and consider whether we need to move it around and/or change other text.

**Comment by aspiers** [comment]
The main goals being:

- Keep it super super easy to understand, instead of asking the user to imagine they were one of their PVPs looking at their profile and then figure out how their own profile would look when presented as a potential swap to that PVP.
- Keep it short

**Comment by baob** [comment]
> I suggest the first step is to to produce the new version of the interpretation text as suggested above in the same place it currently is,

Here you go

<img width="994" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/016d09b3-be12-4f08-8d0d-91395b5c92d0">

**Comment by baob** [comment]
How about this @tdg @aspiers 

<img width="723" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/fb2783ab-e32a-4ec7-9ed0-e92b04e23bfd">

**Comment by aspiers** [comment]
Looks great!  Only tiny nitpick I can think of is that "in the polls" might be interpreted as country-wide, so how about changing to "in the polls for your constituency" or even "in the polls for $CONSTITUENCY"?

**Comment by baob** [comment]
Now ....

<img width="694" alt="image" src="https://github.com/swapmyvote/swapmyvote/assets/55932/a4da8994-d28d-4fb2-b476-a391196b73da">

**Comment by tdg** [comment]
Fantastic

**Comment by aspiers** [comment]
Reopening as I've had to revert this in production due to instability.

**Comment by aspiers** [comment]
@baob Also by not showing the page to several thousand existing users who have already set their willing party, I think this greatly diminished the value of the feature since it's only visible to new sign-ups or those who decided to edit their willing party.  So the original idea of a new DB flag tracking whether users have properly reviewed their willing party choice still makes a lot of sense to me.

**Comment by baob** [comment]
> So the original idea of a new DB flag tracking whether users have properly reviewed their willing party choice still makes a lot of sense to me.

I think it only makes sense if you can get all those users who previously set willing/constituency to visit the review page, perhaps by changing the login flow or something else. Otherwise the new DB field will make next to no difference as they will carry on using their unverified selection.

**Comment by aspiers** [comment]
[**@baob**](https://github.com/baob) commented on [July 3, 2024 2:35 PM](https://github.com/swapmyvote/swapmyvote/issues/905#issuecomment-2206096302 "Wed Jul 03 2024 14:35:50 GMT+0100 - Replied by Github Reply Comments"):
> > So the original idea of a new DB flag tracking whether users have properly reviewed their willing party choice still makes a lot of sense to me.
> 
> I think it only makes sense if you can get all those users who previously set willing/constituency to visit the review page

Sure.

> perhaps by changing the login flow or something else.

No, simply by making it the default page if they haven't reviewed and haven't already offered or confirmed a swap.

**Comment by baob** [comment]
Remaining issues logged in #960
