### ISSUE TITLE
Gentler introduction to our swap matching methodology

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#906]
Home page starts with the premise "swapping is possible" then goes straight into "so what's your preferred party" without first laying out why we're asking that particular question (which is rooted in our chosen methodology for matching voters for a swap.

Solutions could be anything from a re-designing the whole on-boarding flow, to just some simple wordsmithing.

**Comment by aspiers** [comment]
I don't think we should spend any significant time on anything not manageable in the next 2-3 days.  With (a lot of) luck this will be the last ever election which needs vote swapping.

**Comment by aspiers** [comment]
So to be clear, I mean we should think about simple wordsmithing and not spend time on considering huge redesigns of the whole flow.
