### ISSUE TITLE
Maybe upgrade Airbrake

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#909]
We're currently on the free plan which may even be grandfathered at this point:

![image](https://github.com/swapmyvote/swapmyvote/assets/100738/af09483e-cd05-4d00-b8e1-bb1c64247870)

I miss deploy tracking which I think we used to get for free, and is useful for figuring out whether issues are related to certain deployments.

The difference to the next plan up is as follows:

![image](https://github.com/swapmyvote/swapmyvote/assets/100738/d71c4508-04fa-4db6-9087-44ce9b129c29)
![image](https://github.com/swapmyvote/swapmyvote/assets/100738/3ba13cc2-2734-458a-89bd-506af541ac33)

but I'm not sure if we go to that whether we would lose the ability to revert to the free plan later.  @tdg thoughts?

**Comment by tdg** [comment]
It sounds like we can't stay in free anyway? 

If we need to spend some money that is okay

**Comment by aspiers** [comment]
No I suspect we can stay in free indefinitely.  Airbrake is bloody good actually, just rediscovering how useful it is.

**Comment by aspiers** [comment]
Upgraded to Essential
