### ISSUE TITLE
consider tweaking potential swaps construction algorithm for order / length

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#911]
When creating potential swaps, we currently alternate between marginal (if available) and random.  This means that when there are sufficient marginals, we're offering candidates via this template:

1. MARGINAL
2. RANDOM
3. MARGINAL
4. RANDOM
5. MARGINAL

If there are only two marginals, it looks like this:

1. MARGINAL
2. RANDOM
3. MARGINAL
4. RANDOM
5. RANDOM

If there is only one marginal, it looks like this:

1. MARGINAL
2. RANDOM
3. RANDOM
4. RANDOM
5. RANDOM

and of course if there are no marginals then all are random.

Some arguments for always keeping randoms in the mix have resurfaced in https://github.com/swapmyvote/swapmyvote/issues/826#issuecomment-2198243785:

1. We don't want to rock the boat too much, we don't want the pot of potentials to dry up, so lets keep the random element in just in case there aren't any battlefield seats.
2. It's good to have some less random swaps available so people can recognise the good ones when they see them
3. It's important that everyone who offers a swap is actually offered as a PVP somewhere, otherwise we're not really doing our side of the bargain.
4. We don't know if a user _really_ wants a battlefield constituency, so let's continue to give them some of the same old random stuff just in case.

Personally I find 1-3 pretty convincing, and 4 more dubious, but three arguments are good enough to keep randoms in the mix.

The question then becomes: should we keep the current templates / algorithm as detailed above, or tweak it?

For example, we could tweak it to this algorithm:

- Take as many marginals as we can find, up to a max of 3.
- Fill the remaining with randoms, so that we have 5 PVPs in total.

This would simply change the ordering of the first two templates above (but not the third), so is not a major change

## Advantages

- It still satisfies all four arguments listed above.
- It has the additional key benefit of maximising impact under the normal strategy of preferring to swap with marginals.

## Disadvantages

- Users not in marginals always appear below users in marginals.

# Other alternative algorithms

- We could extend it from 5 PVPs to 6 / 7 / whatever.
- Any others?

**Comment by tdg** [comment]
Is there not perhaps a potential new class, based on annotations, that could be in the distribution?

**Comment by baob** [comment]
> * Take as many marginals as we can find, up to a max of 3.
> * Fill the remaining with randoms, so that we have 5 PVPs in total.

That's exactly what happens right now. Marginals at the top of the list.

**Comment by aspiers** [comment]
[**@baob**](https://github.com/baob) commented on [June 29, 2024 5:21 PM](https://github.com/swapmyvote/swapmyvote/issues/911#issuecomment-2198250602 "Sat Jun 29 2024 17:21:13 GMT+0100 - Replied by Github Reply Comments"):
> > *   Take as many marginals as we can find, up to a max of 3.
> > *   Fill the remaining with randoms, so that we have 5 PVPs in total.
> 
> That's exactly what happens right now. Marginals at the top of the list.

Not according to this code?

https://github.com/swapmyvote/swapmyvote/blob/20f89aa163b263067c2e091a66f16794013caf48/app/models/user.rb#L68-L77

**Comment by baob** [comment]
The 'pot' of selections is sorted by 'marginal score' before presentation to the voter.

And because the marginal algorithm is first in the list, it. always fills 3 places if there are marginal selections available.

**Comment by aspiers** [comment]
So then what's the point of this even/odd logic?

**Comment by baob** [comment]
It allows either algorithm to run out of entries, to be filled by the other algorithm

**Comment by baob** [comment]
> Is there not perhaps a potential new class, based on annotations, that could be in the distribution?

That's what I was proposing in #826 I think (which led to this). What did you have in mind @tdg ?

**Comment by aspiers** [comment]
[**@baob**](https://github.com/baob) commented on [June 29, 2024 5:27 PM](https://github.com/swapmyvote/swapmyvote/issues/911#issuecomment-2198253286 "Sat Jun 29 2024 17:27:38 GMT+0100 - Replied by Github Reply Comments"):
> It allows either algorithm to run out of entries, to be filled by the other algorithm

I'm hopelessly confused now :laughing: 

You mean that it goes like this?

1. Odd -> choose as many marginals as possible
2. Even -> fill the rest with randoms
3. END, since we already have the max needed (5)

That doesn't match my reading of the existing code at all ... but even if I'm misreading, I can't see the point of the odd/even logic because it only uses odd once, then even once, then ends.

**Comment by baob** [comment]
I think the probable action out of this is not to necessarily change the algorithm, but at least explain how it works, why it is the way it is.

**Comment by aspiers** [comment]
@baob One thing I found a tiny bit confusing about the current code is the use of the `method` callback.  I think it would be clearer if instead of

https://github.com/swapmyvote/swapmyvote/blob/42b91bcd73feab61e90fa1d2a712bed50db263ee/app/models/user.rb#L97-L99

we had two subclasses of `SwapTrier` (which could be renamed to `SwapFinder`), and then the chooser could be told to round-robin across all the instances passed to it, and then remove finders from the round-robin once they can't find any more swaps.  This simplifies things quite a bit:

```ruby
    chooser = SwapTypeChooser.new(
      MarginalSwapFinder.new(number * 2),
      RandomSwapFinder.new(number * 2),
    )

    while potential_swaps.reload.count < number
      chooser.next_finder.find
      break if chooser.ran_out_of_finders
    end
```

**Comment by baob** [comment]
Follow-up issues created, I'm assuming this can be closed now. @aspiers please re-open or create another issue if I'm wrong.

**Comment by aspiers** [comment]
I think that's fine.  Essentially it already works the way I proposed, due to [the undocumented sorting by marginality which happens at the end](https://github.com/swapmyvote/swapmyvote/issues/911#issuecomment-2198252818).
