### ISSUE TITLE
submit 1024x1024 app icon to facebook

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#93]
We need to submit an app icon for the production facebook app:

![image](https://user-images.githubusercontent.com/100738/69148524-66a64400-0acc-11ea-87c8-a33100c08d80.png)

**Comment by tdg** [comment]
![SwapMyVote-logos-2019-1024x1024](https://user-images.githubusercontent.com/95868/69151608-d6b7c880-0ad2-11ea-8aa7-1bcfa61134c1.png)
How's this @aspiers?

**Comment by aspiers** [comment]
I'm not personally wild on the colour but I defer all design decisions to you and whomever else you trust for that ;-)  All I care about here is keeping facebook happy so we can get the app review through.  I'll submit for staging too, just for good measure.

**Comment by aspiers** [comment]
But out of curiosity, why is it magenta when our site has a blue logo?

**Comment by aspiers** [comment]
Changed to M2 now that the most urgent aspect has been addressed.  We can debate colours at our leisure ;-)

**Comment by aspiers** [comment]
#100 updates the icon to match.

**Comment by tdg** [comment]
Part of #100
