### ISSUE TITLE
Facebook app needs business verification

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#95]
https://developers.facebook.com/apps/377810399053422/settings/basic/?business_id=1071966416290174 has:

![image](https://user-images.githubusercontent.com/100738/69155013-e89c6a00-0ad8-11ea-91e3-f941ed8e2a4e.png)

**Comment by aspiers** [comment]
See https://developers.facebook.com/docs/marketplace/realestate/business-verification/ for help on how to verify.

**Comment by aspiers** [comment]
@tdg AFAICS this can only be done by you as the business manager of the SMV business registered with facebook.

**Comment by tdg** [comment]
Icon submitted and verification underway

**Comment by tdg** [comment]
Verified
![Screen Shot 2019-11-21 at 12 44 50](https://user-images.githubusercontent.com/95868/69339256-d6e3cf80-0c5c-11ea-9e7b-65b0ee7edce9.png)
