### ISSUE TITLE
System error reports this morning

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#952]
Coming in in email and Twitter 

"Hi There,
When I click 'offer to swap' I get an error. I've tried with a few people now? Any advice?
THanks
Will"
![image](https://github.com/swapmyvote/swapmyvote/assets/95868/2e40103d-f20a-4589-92c2-70082f934182)

**Comment by baob** [comment]
May be connected to #950 and #951

**Comment by stevebaxter** [comment]
As a workaround, try editing the user from the top-right of the page and making sure you have a mobile number.

**Comment by tdg** [comment]
Hi, 
As requested, a quick email to say I got an error when I was trying to swap my vote. It occurred when I’d picked someone to swap with and clicked to swap. I’m on an iPad running iOS 16.7.6 using Safari browser, if that’s any use to know. 

Hope it can be fixed in time for the election 🤞
Thanks for creating the site. 
CD

**Comment by aspiers** [comment]
@tdg This should be fixed now, please just ask them to try again.
